CREATE OR ALTER PROCEDURE [dbo].[RSP_KOTREPORT]
--DECLARE 
@DATE1 DATETIME,
@DATE2 DATETIME,
@WAITER VARCHAR(50)='%',
@TBLNAME VARCHAR(25) = '%',
@TBLGROUP VARCHAR(50) = '%',
@OPT_REPTYPE VARCHAR(20) = '%',
@KOTTYPE TINYINT = 100,
@DIVISION VARCHAR(3) = '%'
AS
EXEC NSP_KOTREPORT @DATE1, @DATE2, @WAITER, @TBLNAME, @TBLGROUP, @OPT_REPTYPE, @KOTTYPE, @DIVISION

