IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'trnMain_TaxDetails')
CREATE TABLE trnMain_TaxDetails
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	taxName VARCHAR(100) NOT NULL,
	taxAccount VARCHAR(25) NOT NULL,
	taxableAmount DECIMAL(24,12) NOT NULL,
	taxAmount DECIMAL(24,12) NOT NULL,
	CONSTRAINT FK_trnMain_TaxDetails FOREIGN KEY (VCHRNO, VoucherType) REFERENCES TRNMAIN (VCHRNO, VoucherType) ON DELETE CASCADE,
	CONSTRAINT FK_trnMain_TaxDetails_Account FOREIGN KEY (taxAccount) REFERENCES RMD_ACLIST (ACID),
	CONSTRAINT PK_trnMain_TaxDetails PRIMARY KEY (VCHRNO, VoucherType, taxName),
	CONSTRAINT CHECK_trnMain_TaxDetails CHECK (VoucherType IN ('TI', 'CN'))
)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'trnProd_TaxDetails')
CREATE TABLE trnProd_TaxDetails
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	SNO INT NOT NULL,
	taxName VARCHAR(100) NOT NULL,
	taxAccount VARCHAR(25) NOT NULL,
	taxableAmount DECIMAL(24,12) NOT NULL,
	taxAmount DECIMAL(24,12) NOT NULL,
	CONSTRAINT FK_trnProd_TaxDetails FOREIGN KEY (VCHRNO, VoucherType) REFERENCES TRNMAIN (VCHRNO, VoucherType) ON DELETE CASCADE,
	CONSTRAINT FK_trnProd_TaxDetails_Account FOREIGN KEY (taxAccount) REFERENCES RMD_ACLIST (ACID),
	CONSTRAINT FK_trnProd_TaxDetails_Product FOREIGN KEY (MCODE) REFERENCES MENUITEM (MCODE),
	CONSTRAINT PK_trnProd_TaxDetails PRIMARY KEY (VCHRNO, VoucherType, MCODE, SNO, taxName),
	CONSTRAINT CHECK_trnProd_TaxDetails CHECK (VoucherType IN ('TI', 'CN'))
)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'abbProd_TaxDetails')
CREATE TABLE abbProd_TaxDetails
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	SNO INT NOT NULL,
	taxName VARCHAR(100) NOT NULL,
	taxAccount VARCHAR(25) NOT NULL,
	taxableAmount DECIMAL(24,12) NOT NULL,
	taxAmount DECIMAL(24,12) NOT NULL,
	CONSTRAINT FK_abbProd_TaxDetails FOREIGN KEY (VCHRNO, VoucherType) REFERENCES ABBMAIN (VCHRNO, VoucherType) ON DELETE CASCADE,
	CONSTRAINT FK_abbProd_TaxDetails_Account FOREIGN KEY (taxAccount) REFERENCES RMD_ACLIST (ACID),
	CONSTRAINT FK_abbProd_TaxDetails_Product FOREIGN KEY (MCODE) REFERENCES MENUITEM (MCODE),
	CONSTRAINT PK_abbProd_TaxDetails PRIMARY KEY (VCHRNO, VoucherType, MCODE, SNO, taxName),
	CONSTRAINT CHECK_abbProd_TaxDetails CHECK (VoucherType = 'SI')
)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'abbMain_TaxDetails')
CREATE TABLE abbMain_TaxDetails
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	taxName VARCHAR(100) NOT NULL,
	taxAccount VARCHAR(25) NOT NULL,
	taxableAmount DECIMAL(24,12) NOT NULL,
	taxAmount DECIMAL(24,12) NOT NULL,
	CONSTRAINT FK_abbMain_TaxDetails FOREIGN KEY (VCHRNO, VoucherType) REFERENCES ABBMAIN (VCHRNO, VoucherType) ON DELETE CASCADE,
	CONSTRAINT FK_abbMain_TaxDetails_Account FOREIGN KEY (taxAccount) REFERENCES RMD_ACLIST (ACID),
	CONSTRAINT PK_abbMain_TaxDetails PRIMARY KEY (VCHRNO, VoucherType, taxName),
	CONSTRAINT CHECK_abbMain_TaxDetails CHECK (VoucherType = 'SI')
)