CREATE OR ALTER   PROCEDURE [dbo].[SP_ANNEX7]
	@DATE1 DATETIME,
	@DATE2 DATETIME
AS
SELECT FISCAL_YEAR, BILL_NO, CUSTOMER_NAME, CUSTOMER_PAN, BILL_DATE,AMOUNT, DISCOUNT, TAXABLE_AMOUNT, TAX_AMOUNT,TOTAL_AMOUNT, IS_PRINTED, IS_ACTIVE, PRINTED_TIME, [PRINT NOS],ETERED_BY, PRINTED_BY, EDATE, Stamp, 
SYNC_WITH_IRD, ISREALTIME, Payment_Method, VAT_Refund_Amount, Transaction_Id FROM VIEW_ANNEX7 WHERE BILL_DATE BETWEEN @Date1 AND @Date2