CREATE OR ALTER  VIEW [dbo].[VIEW_ANNEX7]
AS
SELECT A.FISCAL_YEAR,A.BILL_NO,A.CUSTOMER_NAME,A.CUSTOMER_PAN,A.BILL_DATE,A.AMOUNT,A.DISCOUNT,A.TAXABLE_AMOUNT,A.TAX_AMOUNT,A.TAXABLE_AMOUNT+A.NONTAXABLE+TAX_AMOUNT Total_Amount,
A.IS_PRINTED,A.IS_ACTIVE,A.PRINTED_TIME,ISNULL(B.PRINTNOS,1) [PRINT NOS],A.ETERED_BY,A.PRINTED_BY,A.EDATE,A.Stamp,
ISNULL(X.SYNC_WITH_IRD,'NO') SYNC_WITH_IRD,ISNULL(X.ISREALTIME,'NO') ISREALTIME, A.TRNMODE Payment_Method, BOPI.VatRefund VAT_Refund_Amount, BOPI.PSO_TranId Transaction_Id
 FROM
(
	SELECT PHISCALID FISCAL_YEAR, VCHRNO BILL_NO,BILLTO CUSTOMER_NAME,BILLTOTEL CUSTOMER_PAN,TRNDATE BILL_DATE,TAXABLE+NONTAXABLE+DCAMNT  AMOUNT,DCAMNT DISCOUNT,TAXABLE TAXABLE_AMOUNT,VATAMNT TAX_AMOUNT,'YES' IS_PRINTED, dbo.IsInvoiceActive(VCHRNO,DIVISION,PhiscalID) IS_ACTIVE,TRNTIME PRINTED_TIME,NONTAXABLE,
	TRNUSER ETERED_BY,TRNUSER PRINTED_BY,TRNDATE AS EDATE,STAMP,DIVISION,PhiscalID, TRNMODE  FROM RMD_TRNMAIN WHERE LEFT(VCHRNO,2) IN ('SI','TI','RE')
) A LEFT JOIN
(
	SELECT VCHRNO,COUNT(VCHRNO) + 1 PRINTNOS,DIVISION FROM  tblPrintLog GROUP BY VCHRNO,DIVISION
) B  ON A.BILL_NO = B.VCHRNO AND A.DIVISION = B.DIVISION
LEFT JOIN 
(
	SELECT VCHRNO,DIVISION,
	CASE WHEN STATUS = 0 THEN 'YES' ELSE 'NO' END SYNC_WITH_IRD,
	CASE WHEN ISNULL(ISREALTIME, 0) = 0 THEN 'NO' ELSE 'YES' END ISREALTIME
	FROM TBLSYNCLOG
) X ON A.BILL_NO = X.VCHRNO AND A.DIVISION = X.DIVISION
LEFT JOIN RMD_BillOnlinePaymentInfo BOPI ON A.BILL_NO = BOPI.VCHRNO