IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_RATE' AND COLUMN_NAME = 'IntervalLimitBy')
ALTER TABLE DISCOUNT_RATE ADD IntervalLimitBy TINYINT NOT NULL, CONSTRAINT DF_DISCOUNT_RATE_IntervalLimitBy DEFAULT (0) FOR IntervalLimitBy WITH VALUES

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_RATE' AND COLUMN_NAME = 'LimitIntervalReset')
ALTER TABLE DISCOUNT_RATE ADD LimitIntervalReset TINYINT NOT NULL, CONSTRAINT DF_DISCOUNT_RATE_LimitIntervalReset DEFAULT (0) FOR LimitIntervalReset WITH VALUES
	
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_RATE' AND COLUMN_NAME = 'IntervalLimitQty')	
ALTER TABLE DISCOUNT_RATE ADD IntervalLimitQty NUMERIC(18,0) NOT NULL, CONSTRAINT DF_DISCOUNT_RATE_IntervalLimitQty DEFAULT (0) FOR IntervalLimitQty WITH VALUES
	
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_RATE' AND COLUMN_NAME = 'IntervalLimitAmount')
ALTER TABLE DISCOUNT_RATE ADD IntervalLimitAmount NUMERIC(18,0) NOT NULL, CONSTRAINT DF_DISCOUNT_RATE_IntervalLimitAmount DEFAULT (0) FOR IntervalLimitAmount WITH VALUES

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_RATE' AND COLUMN_NAME = 'TRNUSER')
ALTER TABLE DISCOUNT_RATE ADD TRNUSER VARCHAR(30) NULL, CONSTRAINT FK_DISCOUNT_RATE_USERPROFILES FOREIGN KEY (TRNUSER) REFERENCES USERPROFILES(UNAME)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_SCHEMEDISCOUNT' AND COLUMN_NAME = 'TRNUSER')
ALTER TABLE DISCOUNT_SCHEMEDISCOUNT ADD TRNUSER VARCHAR(30) NULL, CONSTRAINT FK_DISCOUNT_SCHEMEDISCOUNT_USERPROFILES FOREIGN KEY (TRNUSER) REFERENCES USERPROFILES(UNAME)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DISCOUNT_SCHEMEDISCOUNT' AND COLUMN_NAME = 'IsActive')
ALTER TABLE DISCOUNT_SCHEMEDISCOUNT ADD IsActive BIT NOT NULL DEFAULT (0) WITH VALUES

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Discount_SchemeDiscount' AND COLUMN_NAME = 'MCAT')
ALTER TABLE Discount_SchemeDiscount ADD MCAT VARCHAR(100) NULL, CONSTRAINT FK_Discount_SchemeDiscount_MCAT FOREIGN KEY (MCAT) REFERENCES MCAT(MENUCAT)