IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EpaymentStatus')
CREATE TABLE EpaymentStatus 
(
	[GUID] VARCHAR(50) NOT NULL, 
	TRNDATE DATETIME NOT NULL, 
	BillAmount DECIMAL(12,2) NOT NULL, 
	TRNUSER VARCHAR(25) NOT NULL, 
	CONSTRAINT PK_EpaymentStatus PRIMARY KEY ([GUID])
) 

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Smart QR')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('Smart QR', '', 'EPAYMENT')

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'FonePay')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('FonePay', '', 'EPAYMENT')

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Khalti')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('Khalti', '', 'EPAYMENT')

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'FinPOS')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('FinPOS', '', 'EPAYMENT')

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'MOCO')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('MOCO', '', 'EPAYMENT')

IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Hamro Pay')
INSERT INTO PaymentModes (PAYMENTMODENAME, ACID, MODE) VALUES ('Hamro Pay', '', 'EPAYMENT')

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'CellPay')
DELETE FROM PaymentModes WHERE PAYMENTMODENAME = 'CellPay'


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Discount_Rate' AND COLUMN_NAME = 'TenderMode')
ALTER TABLE Discount_Rate ADD TenderMode VARCHAR(50) NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Discount_Rate' AND COLUMN_NAME = 'MaxDiscount')
ALTER TABLE Discount_Rate ADD MaxDiscount DECIMAL (12,2) NOT NULL, CONSTRAINT DF_DiscountRate_MaxDiscount DEFAULT (0) FOR MaxDiscount WITH VALUES