IF OBJECT_ID('RMD_KOTMAIN') IS NOT NULL AND OBJECT_ID('KOT_Estimate') IS NULL
CREATE TABLE KOT_Estimate
(
	KotId INT NOT NULL, 
	Division CHAR(3) NOT NULL, 
	TrnDate DATETIME NOT NULL,
	TableNo VARCHAR(50) NOT NULL, 
	TotAmnt DECIMAL(24,12) NOT NULL, 
	Discount DECIMAL(24,12) NOT NULL, 
	Taxable DECIMAL(24,12) NOT NULL, 
	NonTaxable DECIMAL(24,12) NOT NULL, 
	VAT DECIMAL(24,12) NOT NULL, 
	NetAmnt DECIMAL(24,12) NOT NULL,
	DisRate  DECIMAL(24,12) NOT NULL,
	TrnUser VARCHAR(30) NOT NULL,
	CONSTRAINT PK_KOT_Estimate PRIMARY KEY (KotId),
	CONSTRAINT FK_KOT_Estimate FOREIGN KEY (KotId) REFERENCES RMD_KOTMAIN(KotId),
	CONSTRAINT FK_KOT_Estimate_Division FOREIGN KEY (Division) REFERENCES Division(Initial),
	CONSTRAINT FK_KOT_Estimate_User FOREIGN KEY (TrnUser) REFERENCES UserProfiles(UName)
)

IF OBJECT_ID('RMD_KOTMAIN') IS NOT NULL AND OBJECT_ID('KotProd_Estimate') IS NULL
CREATE TABLE KotProd_Estimate
(
	KotId INT NOT NULL, 
	Division CHAR(3) NOT NULL, 
	MCode VARCHAR(25) NOT NULL,	
	Unit VARCHAR(25) NOT NULL,
	Quantity DECIMAL(12,3) NOT NULL, 
	Rate DECIMAL(24,12) NOT NULL,
	CONSTRAINT PK_KotProd_Estimate PRIMARY KEY (KotId, MCode, Unit, Rate),
	CONSTRAINT FK_KotProd_Estimate FOREIGN KEY (KotId) REFERENCES RMD_KOTMAIN(KotId),
	CONSTRAINT FK_KotProd_Estimate_Division FOREIGN KEY (Division) REFERENCES Division(Initial),
	CONSTRAINT FK_KotProd_Estimate_Menuitem FOREIGN KEY (MCode) REFERENCES MenuItem(MCode)
)