IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TableLayout') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TableLayout' AND COLUMN_NAME = 'DIVISION')
	ALTER TABLE TableLayout ADD DIVISION CHAR(3) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TableList') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TableList' AND COLUMN_NAME = 'DIVISION')
	ALTER TABLE TableList ADD DIVISION CHAR(3) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PrintKOT') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PrintKOT' AND COLUMN_NAME = 'DIVISION')
	ALTER TABLE PrintKOT ADD DIVISION CHAR(3) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PRINTKOT_LOG') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRINTKOT_LOG' AND COLUMN_NAME = 'DIVISION')
	ALTER TABLE PRINTKOT_LOG ADD DIVISION CHAR(3) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RMD_KOTPROD') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_KOTPROD' AND COLUMN_NAME = 'guid')
    ALTER TABLE RMD_KOTPROD ADD guid VARCHAR(50) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RMD_KOTPROD') 
	AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_KOTPROD' AND COLUMN_NAME = 'refGuid')
    ALTER TABLE RMD_KOTPROD ADD refGuid VARCHAR(50) NULL										