CREATE OR ALTER PROC OSP_GetBillPreviewProd
--DECLARE 
@VCHRNO VARCHAR(25) 
AS
--SELECT @VCHRNO ='SI11-MMH-81/82'
IF OBJECT_ID('TEMPDB..#SalesReturn') IS NOT NULL DROP TABLE #SalesReturn
SELECT TM.REFBILL,TP.MCODE, TP.UNIT, ISNULL(TP.ALTUNIT, TP.UNIT) ALTUNIT, ISNULL(TP.BC, '') BC, ISNULL(TP.BATCH, '') BATCH, ISNULL(TP.ITEMDESC, MI.DESCA) ITEMDESC
	, SUM(TP.ALTQTY_IN) ALTQTY_IN, SUM(TP.Quantity) Quantity, SUM(TP.REALQTY_IN) REALQTY_IN, SUM(TPS.PointRedeemValue) PointRedeemValue 
	INTO #SalesReturn FROM TRN_TRNMAIN TM 
	JOIN TRNPROD TP ON TM.VCHRNO = TP.VCHRNO 
	JOIN MENUITEM MI ON TP.MCODE = MI.MCODE 
	LEFT JOIN RMD_TRNPROD_STATUS TPS ON TP.VCHRNO = TPS.VCHRNO AND TP.SNO = TPS.SNO
	WHERE TM.REFBILL = @VCHRNO
	GROUP BY TP.MCODE, TP.UNIT, TP.ALTUNIT, TP.ITEMDESC, MI.DESCA, TP.BC, TP.BATCH,TM.REFBILL

SELECT distinct MI.MENUCODE,trp.SNO,bd.SIZE,bd.COLOR,ISNULL(TRP.ITEMDESC, MI.DESCA) ITEMDESC, trp.Quantity, COALESCE(NULLIF(trp.AltQty,0), TRP.ALTQTY_IN) AltQty,ISNULL(A.ALTQTY_IN,0) SalesReturnQty,MI.MCODE,TRP.UNIT,TRP.RATE, TRP.ALTUNIT, TRP.ALTRATE, TRP.REALRATE, TRP.AMOUNT,TRP.DISCOUNT,MI.VAT,
TRP.NETAMOUNT,TRP.TAXABLE,VEHICLEENGINENO,VEHICLECHASISNO,VEHICLEREGISTRATIONNO,VEHICLEMODEL,MI.PTYPE  
from SALES_TRNPROD as trp 
join MENUITEM as MI on trp.MCODE = mi.MCODE  
left join vwBarcode_Detail bd on bd.barcode=trp.BC 
left join #SalesReturn A on A.REFBILL = trp.VCHRNO AND A.MCODE = MI.MCODE
where trp.VCHRNO = @VCHRNO

IF OBJECT_ID('TEMPDB..#SalesReturn') IS NOT NULL DROP TABLE #SalesReturn