CREATE OR ALTER PROC OSP_GetSupplierWiseItemForPO  
--Declare
@SUPCODE VARCHAR(25),  
@PhiscalID VARCHAR(10),  
@RateGroupId INT  = 1,
@Division VARCHAR(3) = '%'
AS  
--SELECT @SUPCODE = 'PA131', @PhiscalID = '80/81', @RateGroupId = 0, @Division = 'SBP'

DECLARE @BCStock BIT  
SELECT @BCStock = CONVERT(BIT,COALESCE(EnableBarcodeDetails,0)) & CONVERT(BIT,COALESCE(HasVehicleSale,0)) FROM SETTING  

SELECT *, (SELECT SUM(RealQty - REALQTY_IN) FROM RMD_TRNMAIN c INNER JOIN RMD_SALESPROD B ON c.VCHRNO=B.VCHRNO AND c.DIVISION = B.DIVISION AND c.PhiscalID= B.PhiscalID WHERE B.MCODE =a.mcode AND C.VoucherType IN ('SI', 'TI', 'CN') 
AND C.TRNDATE >= A.LastPurchaseDate) PeriodicSalesQty   
FROM  
(  
	SELECT BC.BCODE BC, a.mcode, A.menucode,A.desca ITEMDESC, A.Prate_A rate, A.Baseunit  UNIT,A.Mcat,A.MGROUP, CAST(ISNULL(C.RG_RATE, A.RATE_A) * IIF(A.VAT = 1, 1.13, 1) AS Numeric(18,2)) SPRICE, A.VAT ISVAT, A.LPDATE LastPurchaseDate,Z.STOCK, Z.outletStock

	FROM menuitem a WITH (NOLOCK) LEFT JOIN BARCODE BC WITH (NOLOCK) ON IIF(@BCStock=1,A.MCODE,'') = BC.MCODE   
	OUTER APPLY dbo.fnGetRateGroup(A.MCODE, A.RATE_A, @RateGroupId) C  
	LEFT JOIN  
	(  
		SELECT MI.MCODE, IIF(@BCStock=1,BC,'') BC, A.outletStock, A.STOCK FROM MENUITEM MI LEFT JOIN
		(
			SELECT DISTINCT MCODE, IIF(@DIVISION = '%', '%', DIVISION) DIVISION, IIF(@BCStock=1,BC,'') BC
			, SUM(REALQTY_IN - REALQTY) OVER (PARTITION BY MCODE) STOCK
			, SUM(REALQTY_IN - REALQTY) OVER (PARTITION BY IIF(@DIVISION = '%', '%', DIVISION),MCODE,IIF(@BCStock=1,BC,'')) outletStock FROM RMD_TRNPROD WITH (NOLOCK)
		) A ON MI.MCODE = A.MCODE WHERE ISNULL(A.DIVISION, @Division) = @Division AND MI.TYPE = 'A'
	) Z ON A.MCODE = Z.MCODE AND IIF(@BCStock=1,BC.BCODE,'') = Z.BC  
	WHERE A.SUPCODE = @SUPCODE AND A.IsActive = 1  
) A 