CREATE OR ALTER PROC [dbo].[OSP_GenerateGiftVoucher]
--DECLARE 
@DATE1 DATE, 
@DATE2 DATE,
@QualifiedSalesAmount NUMERIC(18,2),
@Rate NUMERIC(5,2),
@Scheme VARCHAR(25) = '%'
AS
--SET @DATE1 = '2020-07-16'
--SET @DATE2 = '2021-07-15'
--SET @QualifiedSalesAmount = 1000
--SET @RATE = 2
SELECT ROW_NUMBER() OVER (ORDER BY A.MEMBERNO) GV_NUMBER, M.FNAME MEMBER_NAME, M.T_STREET [ADDRESS], M.MOBILE, M.SCHEMEID, A.* FROM
(
	SELECT MEMBERNO, COUNT(1) NO_OF_BILLS, 
	CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN TOTAMNT * -1 ELSE TOTAMNT END)) AMOUNT,
	CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN DCAMNT * -1 ELSE DCAMNT END)) DISCOUNT,
	CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN VATAMNT * -1 ELSE VATAMNT END)) VAT,
	CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN NETAMNT * -1 ELSE NETAMNT END)) NET_SALES,
	CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN NETAMNT * -1 ELSE NETAMNT END) * @RATE /100) GIFT_VOUCHER_AMOUNT FROM RMD_TRNMAIN 
	WHERE VoucherType IN ('SI', 'TI', 'CN') AND MEMBERNO IS NOT NULL
	AND TRNDATE BETWEEN @DATE1 AND @DATE2
	GROUP BY MEMBERNO
	HAVING CONVERT(NUMERIC(18,2),SUM(CASE WHEN VOUCHERTYPE = 'CN' THEN NETAMNT * -1 ELSE NETAMNT END)) > @QualifiedSalesAmount
) A JOIN MEMBERSHIP M ON A.MEMBERNO = M.MEMID
WHERE M.SCHEMEID LIKE @SCHEME