IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Cash' AND ISNULL(SNO, 99) <> 1)
UPDATE PaymentModes SET SNO = 1 WHERE PAYMENTMODENAME = 'Cash'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Credit' AND ISNULL(SNO, 99) <> 2)
UPDATE PaymentModes SET SNO = 2 WHERE PAYMENTMODENAME = 'Credit'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Credit Card' AND ISNULL(SNO, 99) <> 3)
UPDATE PaymentModes SET SNO = 3 WHERE PAYMENTMODENAME = 'Credit Card'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Smart QR' AND ISNULL(SNO, 99) <> 4)
UPDATE PaymentModes SET SNO = 4 WHERE PAYMENTMODENAME = 'Smart QR'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Nepal Pay' AND ISNULL(SNO, 99) <> 5)
UPDATE PaymentModes SET SNO = 5 WHERE PAYMENTMODENAME = 'Nepal Pay'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'FonePay' AND ISNULL(SNO, 99) <> 6)
UPDATE PaymentModes SET SNO = 6 WHERE PAYMENTMODENAME = 'FonePay'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'IME Pay' AND ISNULL(SNO, 99) <> 7)
UPDATE PaymentModes SET SNO = 7 WHERE PAYMENTMODENAME = 'IME Pay'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Khalti' AND ISNULL(SNO, 99) <> 8)
UPDATE PaymentModes SET SNO = 8 WHERE PAYMENTMODENAME = 'Khalti'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'MOCO' AND ISNULL(SNO, 99) <> 9)
UPDATE PaymentModes SET SNO = 9 WHERE PAYMENTMODENAME = 'MOCO'

IF EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Hamro Pay' AND ISNULL(SNO, 99) <> 10)
UPDATE PaymentModes SET SNO = 10 WHERE PAYMENTMODENAME = 'Hamro Pay'
