IF NOT EXISTS (SELECT * FROM PaymentModes WHERE PAYMENTMODENAME = 'Cash' AND SNO = '1')
BEGIN
	UPDATE PaymentModes SET SNO = 99 WHERE ISNULL(SNO,0) <> 99
	UPDATE PaymentModes SET SNO = 1 WHERE PAYMENTMODENAME = 'Cash'
	UPDATE PaymentModes SET SNO = 2 WHERE PAYMENTMODENAME = 'Credit'
	UPDATE PaymentModes SET SNO = 3 WHERE PAYMENTMODENAME = 'Credit Card'
	UPDATE PaymentModes SET SNO = 4 WHERE PAYMENTMODENAME = 'Smart QR'
	UPDATE PaymentModes SET SNO = 5 WHERE PAYMENTMODENAME = 'FonePay'
	UPDATE PaymentModes SET SNO = 6 WHERE PAYMENTMODENAME = 'Khalti'
	UPDATE PaymentModes SET SNO = 7 WHERE PAYMENTMODENAME = 'FinPOS'
	UPDATE PaymentModes SET SNO = 8 WHERE PAYMENTMODENAME = 'MOCO'
	UPDATE PaymentModes SET SNO = 9 WHERE PAYMENTMODENAME = 'Hamro Pay'
END