IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRNPROD_COGS' AND COLUMN_NAME = 'SNO' AND IS_NULLABLE = 'YES')
ALTER TABLE TRNPROD_COGS ALTER COLUMN SNO INT NOT NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ABBPROD_COGS' AND COLUMN_NAME = 'SNO' AND IS_NULLABLE = 'YES')
ALTER TABLE ABBPROD_COGS ALTER COLUMN SNO INT NOT NULL

IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRNPROD_COGS' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE TRNPROD_COGS ADD ROW_VERSION rowversion

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ABBPROD_COGS' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE ABBPROD_COGS ADD ROW_VERSION rowversion

IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRNPROD_COGS' AND COLUMN_NAME = 'ORIGIN_ROW_VERSION')
ALTER TABLE TRNPROD_COGS ADD ORIGIN_ROW_VERSION VARBINARY(25) NULL

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ABBPROD_COGS' AND COLUMN_NAME = 'ORIGIN_ROW_VERSION')
ALTER TABLE ABBPROD_COGS ADD ORIGIN_ROW_VERSION VARBINARY(25) NULL