IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRNPROD_COGS')
CREATE TABLE TRNPROD_COGS
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	BC VARCHAR(50) NULL,
	BATCH VARCHAR(50) NULL,
	SNO INT NOT NULL,
	COSTING_INVOICE VARCHAR(25) NOT NULL,
	Quantity NUMERIC (18,3) NOT NULL,
	CRATE NUMERIC(18,6) NOT NULL,
	STAMP DATETIME NOT NULL DEFAULT (GETDATE()),
	ROW_VERSION rowversion,
	ORIGIN_ROW_VERSION VARBINARY(25) NULL,
	CONSTRAINT PK_TrnProd_COGS PRIMARY KEY(VCHRNO,VoucherType, MCODE,SNO, COSTING_INVOICE, CRATE),
	CONSTRAINT FK_TRNPROD_COGS FOREIGN KEY (VCHRNO, VoucherType) REFERENCES TRNMAIN(VCHRNO, VoucherType) ON DELETE CASCADE
)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ABBPROD_COGS')
CREATE TABLE ABBPROD_COGS
(
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	BC VARCHAR(50) NULL,
	BATCH VARCHAR(50) NULL,
	SNO INT NOT NULL,
	COSTING_INVOICE VARCHAR(25) NOT NULL,
	Quantity NUMERIC (18,3) NOT NULL,
	CRATE NUMERIC(18,6) NOT NULL,
	STAMP DATETIME NOT NULL DEFAULT (GETDATE()),
	ROW_VERSION rowversion,
	ORIGIN_ROW_VERSION VARBINARY(25) NULL,
	CONSTRAINT PK_AbbProd_COGS PRIMARY KEY(VCHRNO, VoucherType, MCODE,SNO, COSTING_INVOICE, CRATE),
	CONSTRAINT FK_ABBPROD_COGS FOREIGN KEY (VCHRNO, VoucherType) REFERENCES ABBMAIN(VCHRNO, VoucherType) ON DELETE CASCADE
)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOGPROD_COGS')
CREATE TABLE LOGPROD_COGS
(
	LOGID INT NOT NULL IDENTITY(1,1),
	LOGDATE DATETIME NOT NULL DEFAULT (GETDATE()),
	LOGUSER VARCHAR(50) NOT NULL,
	LOGACTION VARCHAR(1) NOT NULL,
	VCHRNO VARCHAR(25) NOT NULL,
	VoucherType VARCHAR(2) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	BC VARCHAR(50) NULL,
	BATCH VARCHAR(50) NULL,
	SNO INT NULL,
	COSTING_INVOICE VARCHAR(25) NOT NULL,
	Quantity NUMERIC (18,3) NOT NULL,
	CRATE NUMERIC(18,6) NOT NULL,	
	STAMP DATETIME NOT NULL
)

IF OBJECT_ID('CHECK_TRNPROD_COGS') IS NULL
BEGIN
	ALTER TABLE TRNPROD_COGS WITH CHECK ADD CONSTRAINT CHECK_TRNPROD_COGS CHECK (([VOUCHERTYPE] IN ('TI','CN')))
	ALTER TABLE TRNPROD_COGS CHECK CONSTRAINT [CHECK_TRNPROD_COGS]
END

IF OBJECT_ID('CHECK_ABBPROD_COGS') IS NULL
BEGIN
	ALTER TABLE ABBPROD_COGS WITH CHECK ADD CONSTRAINT CHECK_ABBPROD_COGS CHECK (([VOUCHERTYPE] IN ('SI')))
	ALTER TABLE ABBPROD_COGS CHECK CONSTRAINT [CHECK_ABBPROD_COGS]
END

IF OBJECT_ID('PK_TrnProd_COGS') IS NULL
ALTER TABLE TRNPROD_COGS ADD CONSTRAINT PK_TrnProd_COGS PRIMARY KEY(VCHRNO,VoucherType, MCODE,SNO, COSTING_INVOICE, CRATE)

IF OBJECT_ID('PK_AbbProd_COGS') IS NULL
ALTER TABLE ABBPROD_COGS ADD CONSTRAINT PK_AbbProd_COGS PRIMARY KEY(VCHRNO, VoucherType, MCODE,SNO, COSTING_INVOICE, CRATE)

