IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECEIPEPROD' AND COLUMN_NAME = 'IsTakeAwayItem')
ALTER TABLE RECEIPEPROD ADD  IsTakeAwayItem tinyint

IF EXISTS (SELECT * FROM TableList WHERE TableNo IS NULL)
DELETE FROM TableList WHERE TableNo IS NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ReceipeProd' AND COLUMN_NAME = 'IsActive')
ALTER TABLE ReceipeProd ADD IsActive BIT NOT NULL CONSTRAINT DF_ReceipeProd_IsActive DEFAULT(1) WITH VALUES

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ReceipeProd' AND COLUMN_NAME = 'TrnUser')
ALTER TABLE ReceipeProd ADD TrnUser VARCHAR(30) CONSTRAINT FK_ReceipeProd_TrnUser FOREIGN KEY (TrnUser) REFERENCES UserProfiles(UNAME)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ReceipeMain' AND COLUMN_NAME = 'TrnUser')
ALTER TABLE ReceipeMain ADD TrnUser VARCHAR(30) CONSTRAINT FK_ReceipeMain_TrnUser FOREIGN KEY (TrnUser) REFERENCES UserProfiles(UNAME)

