IF EXISTS(SELECT * FROM SYS.objects WHERE NAME = 'DF__RMD_BILLT__AMOUN__10E07F16' AND type_desc = 'DEFAULT_CONSTRAINT')
BEGIN
	alter table RMD_BILLTENDER DROP CONSTRAINT DF__RMD_BILLT__AMOUN__10E07F16
	alter table RMD_BILLTENDER ALTER COLUMN AMOUNT DECIMAL(25,16) NOT NULL
	ALTER TABLE RMD_BILLTENDER ALTER COLUMN CHANGE DECIMAL(25,16) NOT NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_BILLTENDER' AND COLUMN_NAME = 'CHANGE' AND NUMERIC_SCALE = 0)
ALTER TABLE RMD_BILLTENDER ALTER COLUMN CHANGE NUMERIC(18,2)

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_BILLTENDER' AND COLUMN_NAME = 'CardNo')
ALTER TABLE RMD_BILLTENDER ADD CardNo VARCHAR(100) NULL

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_BILLTENDER' AND COLUMN_NAME = 'CardBalance')
ALTER TABLE RMD_BILLTENDER ADD CardBalance DECIMAL(18,2) NULL