IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_ORDERMAIN' AND COLUMN_NAME = 'RECEIVEBY')
ALTER TABLE RMD_ORDERMAIN ADD RECEIVEBY VARCHAR(50)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_ORDERMAIN' AND COLUMN_NAME = 'BILLTO')
ALTER TABLE RMD_ORDERMAIN ADD BILLTO VARCHAR(250)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_ORDERMAIN' AND COLUMN_NAME = 'BILLTOADD')
ALTER TABLE RMD_ORDERMAIN ADD BILLTOADD VARCHAR(500)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RMD_ORDERMAIN' AND COLUMN_NAME = 'BILLTOTEL')
ALTER TABLE RMD_ORDERMAIN ADD BILLTOTEL VARCHAR(50)