IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALESMAN' AND COLUMN_NAME = 'IsActive')
ALTER TABLE SALESMAN DROP COLUMN IsActive

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALESMAN' AND COLUMN_NAME = 'Status')
ALTER TABLE SALESMAN ADD [Status] BIT NOT NULL DEFAULT(1) WITH VALUES