CREATE OR ALTER PROC SP_GetItemWisePointCalculation
--DECLARE
@JSON VARCHAR(MAX),
@MemberScheme VARCHAR(50) = ''
AS

SET NOCOUNT ON
IF OBJECT_ID('TEMPDB..#TempTable') IS NOT NULL DROP TABLE #TempTable
IF OBJECT_ID('TEMPDB..#RESULT') IS NOT NULL DROP TABLE #RESULT

SELECT A.MCODE INTO #TempTable FROM OPENJSON(@JSON) 
CROSS APPLY OPENJSON(VALUE) 
WITH
(
	MCODE VARCHAR(25) '$.MCODE'
) A


SELECT DISTINCT I.SCHEMEID, I.GRADEVALUE, I.GRADEPOINT, COALESCE(M.MCODE,P.MCODE,MG.MCODE, MC.MCODE) Mcode INTO #RESULT from MEMGRADE I 
LEFT JOIN MENUITEM  M on M.MCODE = I.MCODE 
LEFT JOIN MENUITEM P  on P.PARENT = I.PARENT 
LEFT JOIN MENUITEM MG ON MG.MGROUP = I.MGroup
LEFT JOIN MENUITEM MC ON MC.MCAT = I.MCAT
JOIN #TempTable S ON I.MCODE = S.MCODE OR P.MCODE = S.MCODE OR MG.MCODE = S.MCODE OR MC.MCODE = S.MCODE
WHERE 
I.SCHEMEID = @MemberScheme

SELECT * FROM #RESULT
UNION ALL
SELECT I.SCHEMEID, I.GRADEVALUE, I.GRADEPOINT, M.MCODE FROM
(
	SELECT * FROM MEMGRADE WHERE SCHEMEID = @MemberScheme AND MGroup IS NULL AND Parent IS NULL AND MCODE IS NULL AND MCAT IS NULL
) I FULL OUTER JOIN
(
	SELECT A.MCODE FROM #TempTable A LEFT JOIN #RESULT B ON A.MCODE = B.Mcode WHERE B.Mcode IS NULL
) M ON 0=0

SET NOCOUNT OFF