IF EXISTS (SELECT * FROM tblDenomination WHERE ISNUMERIC(QTY) = 0)
UPDATE tblDenomination SET QTY = 1 WHERE ISNUMERIC(QTY) = 0

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblDenomination' AND COLUMN_NAME = 'QTY' AND DATA_TYPE = 'int')
ALTER TABLE tblDenomination ALTER COLUMN QTY INT NULL