CREATE OR ALTER VIEW TRNMAIN_BRANCH_OUT  
AS  
SELECT VCHRNO,DIVISION,CHALANNO,TRNDATE,BSDATE,TRN_DATE,BS_DATE ,TRNTIME,TOTAMNT,NETAMNT,TRNMODE,BILLTO,BILLTOADD,TRNUSER,REMARKS,TERMINAL,PhiscalID,EditUser, REFBILL,  STAMP  FROM RMD_TRNMAINS WHERE LEFT(VCHRNO, 2) = 'TO'  
AND (SELECT CentralizedDbMode FROM SETTING) = 0 AND (SELECT ISBRANCH FROM COMPANY) = 1
UNION
SELECT VCHRNO,DIVISION,CHALANNO,TRNDATE,BSDATE,TRN_DATE,BS_DATE ,TRNTIME,TOTAMNT,NETAMNT,TRNMODE,BILLTO,BILLTOADD,TRNUSER,REMARKS,TERMINAL,PhiscalID,EditUser, REFBILL,  STAMP  FROM INVMAIN WHERE LEFT(VCHRNO, 2) = 'TO'