CREATE OR ALTER VIEW [dbo].[TRNPROD_VIEW]
AS

SELECT A.VCHRNO,A.CHALANNO, A.DIVISION, A.MCODE,A.UNIT,B.DESCA,B.SUPCODE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN A.QUANTITY *-1 ELSE A.QUANTITY END AS QUANTITY,
A.REALQTY_IN,A.REALQTY,A.RATE,A.REALRATE,A.OPQTY,A.WAREHOUSE,A.PRATE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN A.AMOUNT *-1 ELSE A.AMOUNT END AS AMOUNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('CN','SR','PR','IR','RE') THEN A.DISCOUNT *-1 ELSE A.DISCOUNT END AS DISCOUNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('CN','SR','PR','IR','RE') THEN A.VAT *-1 ELSE A.VAT END AS VAT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN
	CASE WHEN LEFT(A.VCHRNO,2) IN ('SR') THEN A.AMOUNT *-1 ELSE (A.AMOUNT + A.VAT) *-1 END
ELSE
	CASE WHEN LEFT(A.VCHRNO,2) IN ('SI') THEN A.AMOUNT ELSE (A.AMOUNT + A.VAT) END END AS GROSSAMOUNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN
	CASE WHEN LEFT(A.VCHRNO,2) IN ('SR') THEN (A.AMOUNT-A.DISCOUNT) *-1 ELSE (A.AMOUNT + A.VAT - A.DISCOUNT) *-1 END	
ELSE
	CASE WHEN LEFT(A.VCHRNO,2) IN ('SI') THEN A.AMOUNT - A.DISCOUNT ELSE A.AMOUNT + A.VAT - A.DISCOUNT END END AS NETAMOUNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN A.TAXABLE *-1 ELSE A.TAXABLE END AS TAXABLE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN A.NONTAXABLE *-1 ELSE A.NONTAXABLE END AS NONTAXABLE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SR','CN','PR','IR','RE') THEN A.VRATE *-1 ELSE A.VRATE END AS VRATE,
B.PRATE_A,A.PHISCALID ,LOYALTY,
cast((ISNULL(a.LOYALTY,0)*100)/a.AMOUNT as numeric(10,2)) [LOYALTY DISCOUNT(%)]
FROM RMD_TRNPROD A INNER JOIN MENUITEM B ON A.MCODE = B.MCODE 