IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowComplimentarySales')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowComplimentarySales','Allow Complimentary Sales')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowWholesaleBill')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowWholesaleBill','Allow Wholesale Bill')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'FORCEDAYEND')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('FORCEDAYEND','Force Day End')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'SRATEEDIT')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('SRATEEDIT','Can change Selling Rate')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'DAYENDRIGHT')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('DAYENDRIGHT','Can Day End')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowEstimateBillVoid')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowEstimateBillVoid','Allow Estimate Bill Void')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'VOUCHERPOSTRIGHT')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('VOUCHERPOSTRIGHT','Can Post Vouchers')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowMultiPhiscalYear')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowMultiPhiscalYear','Can login to Previous Fiscal Year')
IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'PRATEEDIT')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('PRATEEDIT','Can change Purchase Rate')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'IsWaiter')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('IsWaiter','User is a Waiter')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'BACKDATEENTRY')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('BACKDATEENTRY','Allow Back Dated Voucher Entry')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowMultiPhiscalYear')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowMultiPhiscalYear','Can login to Previous Fiscal Year')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'ITEMEDITRIGHT')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('ITEMEDITRIGHT', 'Can Decrease Item Qty')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowSalesBelowCRate')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowSalesBelowCRate', 'Allow Sales Below Cost/Purchase Rate.')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'EditSettingRights')
INSERT INTO UserRightsAbb (COLUMN_NAME, [DESCRIPTION]) VALUES ('EditSettingRights','Edit Application Settings')

IF EXISTS (SELECT * from USERRIGHTSABB where COLUMN_NAME = 'EditSettingRights' and [DESCRIPTION] = 'Can Edit Setting Master')
DELETE FROM USERRIGHTSABB where COLUMN_NAME = 'EditSettingRights' and [DESCRIPTION] = 'Can Edit Setting Master'

IF EXISTS (SELECT * from INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserRightsAbb' AND COLUMN_NAME = 'COLUMN_NAME' AND IS_NULLABLE='YES')
ALTER TABLE UserRightsAbb ALTER COLUMN COLUMN_NAME VARCHAR(50) NOT NULL

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'ShowCreditorBalance')
INSERT INTO UserRightsAbb (COLUMN_NAME, [DESCRIPTION]) VALUES ('ShowCreditorBalance','Show Creditor B/L | Ledgers ')

IF NOT EXISTS(SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'disablePrintCashSettlement')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('disablePrintCashSettlement','Disable Settlement Print')

IF EXISTS (SELECT * FROM SETTING WHERE EnableServiceCharge = 1) AND NOT EXISTS (SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'allowTableTransfer')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('allowTableTransfer','Allow Table Transfer')

IF EXISTS (SELECT * FROM SETTING WHERE EnableServiceCharge = 1) AND NOT EXISTS (SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'allowTableSplit')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('allowTableSplit','Allow Table Split')

IF EXISTS (SELECT * FROM SETTING WHERE EnableServiceCharge = 1) AND NOT EXISTS (SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'allowTableMerge')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('allowTableMerge','Allow Table Merge')

IF EXISTS (SELECT * FROM SETTING WHERE EnableServiceCharge = 1) AND NOT EXISTS (SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AUTHORIZE')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AUTHORIZE','Allow Table Cancellation')