IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERPROFILES' AND COLUMN_NAME = 'AllowComplimentarySales')
ALTER TABLE USERPROFILES ADD AllowComplimentarySales TinyInt NOT NULL, 	CONSTRAINT DF_USERPROFILES_AllowComplimentarySales DEFAULT (0) FOR AllowComplimentarySales	

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERPROFILES' AND COLUMN_NAME = 'AllowEstimateBillVoid')
ALTER TABLE USERPROFILES ADD AllowEstimateBillVoid TinyInt NOT NULL, 	CONSTRAINT DF_USERPROFILES_AllowEstimateBillVoid DEFAULT (0) FOR AllowEstimateBillVoid	

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERPROFILES' AND COLUMN_NAME = 'AllowWholesaleBill')
ALTER TABLE USERPROFILES ADD AllowWholesaleBill TinyInt NOT NULL, 	CONSTRAINT DF_USERPROFILES_AllowWholesaleBill DEFAULT (0) FOR AllowWholesaleBill

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERPROFILES' AND COLUMN_NAME = 'AllowMultiPhiscalYear ')
ALTER TABLE USERPROFILES ADD AllowMultiPhiscalYear TinyInt NOT NULL, 	CONSTRAINT DF_USERPROFILES_AllowMultiPhiscalYear  DEFAULT (0) FOR AllowMultiPhiscalYear


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserProfiles' AND COLUMN_NAME = 'AllowSalesBelowCRate')
ALTER TABLE UserProfiles ADD AllowSalesBelowCRate TINYINT

IF NOT EXISTS (SELECT * FROM USERRIGHTSABB WHERE COLUMN_NAME = 'AllowSalesBelowCRate')
INSERT INTO USERRIGHTSABB(COLUMN_NAME, [DESCRIPTION]) VALUES ('AllowSalesBelowCRate', 'Allow Sales Below Cost/Purchase Rate.') 		

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'PASSWORD' AND TABLE_NAME = 'UserProfiles' AND CHARACTER_MAXIMUM_LENGTH = 200)
ALTER TABLE UserProfiles ALTER COLUMN [PASSWORD] VARCHAR(200) NOT NULL

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'PASSWORD' AND TABLE_NAME = '_Log_UserProfiles' AND CHARACTER_MAXIMUM_LENGTH = 200)
ALTER TABLE _Log_UserProfiles ALTER COLUMN [PASSWORD] VARCHAR(200) NOT NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERPROFILES' AND COLUMN_NAME = 'ShowCreditorBalance')
ALTER TABLE USERPROFILES ADD ShowCreditorBalance TinyInt NOT NULL, 	CONSTRAINT DF_USERPROFILES_ShowCreditorBalance  DEFAULT (1) FOR ShowCreditorBalance

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserProfiles' AND COLUMN_NAME = 'allowTableTransfer')
ALTER TABLE UserProfiles ADD allowTableTransfer TINYINT NOT NULL DEFAULT (1) WITH VALUES