CREATE OR ALTER VIEW vwACLIST
AS
SELECT A.SERIAL,A.ACID,A.ACNAME,A.PARENT,A.TYPE,A.OPBAL,A.MAPID,A.IsBasicAc,A.ADDRESS,A.PHONE,A.FAX,A.EMAIL,A.VATNO,A.PType,A.CRLIMIT,A.CRPERIOD,A.SALEREF,A.ACCODE,A.LEVELS
,A.FLGNEW,A.COMMON,A.PATH,A.INITIAL,A.EDATE,A.DISMODE,A.MCAT,A.HASSUBLEDGER,A.RATETYPE,A.INVCHECK,A.LEADTIME,A.AUTOFILLVALUE,A.ACTYPE,A.MAINGROUP,A.CrmCode,B.DIV,A.ISACTIVE
,A.ISCOMMONAC,A.CHANEL,A.Currency,A.GSTTYPE,A.MAILTYPE,A.MOBILE,A.STATE,A.CITY,A.GSTNO,A.ADHARNO,A.ERPPLANTCODE,A.TITLE,A.shortname,A.customerID,A.LANDMARK,A.AREA,A.POSTALCODE
,A.PRICELEVELCONFIG,A.PRICELEVEL,A.PSTYPE,A.TEMPADDRESS,A.CTYPE,A.CATEGORY,A.COMPANYID,A.CBALANCE,A.Channel,A.GEO,A.ROUTE,A.RouteDays,A.SO,A.PMODE,A.UPDATEDDATE
,A.ERPSTOCKLOCATIONCODE,A.DISTRICT,A.CONTACTPERSON,A.CONTACTMOBILE,A.CONTACTEMAIL,A.COM_PREFIX,A.CUS_FIX_DISCOUNT_PER,A.IMPORTERTAG,A.SM,A.SUBCHANNEL,A.STAMP,A.isFDApproved
,A.isRDApproved,A.CUS_Remote_Discount,A.isApproved,A.PCL,A.HSN_SACCODE,A.BANKACCOUNTNUMBER,A.IFCS_CODE,A.BANKBUILDING,A.mode,A.isReverseChargeApplicable,A.isRCMApplicable
,A.isAutoGSTApplicable,A.isTDSapplicable,A.AREA_ID,A.enableDivSelectionTable,A.ISCOMMON,A.DDA_NO,A.NCDA_NO,A.BlockNegativeBalance,A.BANKCODE,A.BANKNAME,A.ISBRANCH,A.BANKID
,A.PCompany,A.PCompanyName,A.ContractPriceId,A.CATEGORY_ID,A.IS_OVERSEAS_PARTY,A.HASTRANSACTION,A.TERMSANDCONDITIONS,A.SALESMANID,A.SUPTYPE,A.TDS_TYPE,A.CustomerType 
FROM RMD_ACLIST A
JOIN
(
	SELECT ACID, STRING_AGG(DIV, ',') DIV FROM RMD_ACLIST_DIVISION WHERE ISACTIVE = 1 GROUP BY ACID
) B ON A.ACID = B.ACID