CREATE OR ALTER VIEW [dbo].[vwBarcode_Detail] 
AS

SELECT MCODE,BCODE, BCODE BARCODE,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.COLOR') ELSE '' END AS COLOR, 
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.SIZE') ELSE '' END AS SIZE,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.MAKE') ELSE '' END AS MAKE,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.GENDER') ELSE '' END AS GENDER,  
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.ORIGIN') ELSE '' END AS ORIGIN,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.FIT') ELSE '' END AS FIT,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.SEASON') ELSE '' END AS SEASON,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.MEASUREMENT') ELSE '' END AS MEASUREMENT,
NULL VEHICLEENGINENO, NULL VEHICLECHASISNO, NULL VEHICLEREGISTRATIONNO, NULL VEHICLEMODEL,
SRATE,UNIT,ISACTIVE,ISDEACTIVE FROM BARCODE WHERE ISJSON(barcodeDetails)>0
UNION ALL
SELECT B.MCODE,B.BCODE, BD.BARCODE, BD.COLOR, BD.SIZE, BD.MAKE, BD.GENDER, BD.ORIGIN, BD.FIT, BD.SEASON, BD.MEASUREMENT
, BD.VEHICLEENGINENO, BD.VEHICLECHASISNO, BD.VEHICLEREGISTRATIONNO, BD.VEHICLEMODEL,B.SRATE, B.UNIT,B.ISACTIVE,B.ISDEACTIVE  FROM BARCODE B 
JOIN BARCODE_DETAIL BD ON B.BCODE = BD.BARCODE
