CREATE OR ALTER VIEW [dbo].[vwBarcode_Detail] 
AS

SELECT MCODE,BCODE, BCODE BARCODE,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.COLOR') ELSE '' END AS COLOR, 
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.SIZE') ELSE '' END AS SIZE,
CASE WHEN ISJSON(barcodeDetails)>0 THEN JSON_VALUE(barcodeDetails,'$.GENDER') ELSE '' END AS GENDER,  
NULL VEHICLEENGINENO, NULL VEHICLECHASISNO, NULL VEHICLEREGISTRATIONNO, NULL VEHICLEMODEL,
SRATE,UNIT,ISACTIVE,ISDEACTIVE FROM BARCODE WHERE ISJSON(barcodeDetails)>0
UNION ALL
SELECT B.MCODE,B.BCODE, BD.BARCODE, BD.COLOR, BD.SIZE, BD.VEHICLEENGINENO, BD.VEHICLECHASISNO, BD.VEHICLEREGISTRATIONNO, BD.VEHICLEMODEL,B.SRATE, B.UNIT,B.ISACTIVE,B.ISDEACTIVE  FROM BARCODE B 
JOIN BARCODE_DETAIL BD ON B.BCODE = BD.BARCODE