CREATE OR ALTER VIEW [dbo].[vwCustomerProfile]
AS
SELECT C.CUSTID, C.MOBILENO, C.CUSTNAME, C.MEMBERNO, C.ADDRESS, C.PANNO,C.IdentityDocument, C.DocumentNo, C.Age,C.Gender,C.CUSTACCOUNT, C.EMAIL, C.BARCODE, M.SCHEMEID, C.CustomerType, COALESCE(C.DOB, M.DOB) DOB, COALESCE(C.WAD, M.WAD) WAD from CUSTOMERPROFILE C 
LEFT JOIN MEMBERSHIP M ON C.MEMBERNO = M.MEMID