CREATE OR ALTER VIEW vwMemberProfile  
AS  
SELECT MEMID CUSTID, MOBILE MOBILENO, TEL_R PHONE, FNAME CUSTNAME, BARCODE MEMBERNO, COALESCE(NULLIF(T_STREET, ''), P_STREET)  [ADDRESS], PANNo, IdentityDocument, DocumentNo, AGE, GENDER, ACCOUNT CUSTACCOUNT, EMAIL, BARCODE, SCHEMEID, CustomerType, DOB, WAD, REFERENCEBY ReferredBy FROM MEMBERSHIP