CREATE OR ALTER   VIEW [dbo].[vwPartyHierarchy]
AS

select RA.ACID,RG.ACNAME  [A/C MAIN GROUP],NULL [A/C GROUP A],NULL [A/C GROUP B],null [A/C GROUP C]
from RMD_ACLIST RA WITH (NOLOCK)  
JOIN RMD_ACLIST RG WITH (NOLOCK)  ON RA.PARENT=RG.ACID
WHERE RG.TYPE = 'G' AND RG.PARENT IN ('PA') AND RA.TYPE = 'A' AND RA.ACID   LIKE 'PA%' 

UNION ALL

SELECT RA.ACID,RG.ACNAME [A/C MAIN GROUP], RC.ACNAME,NULL, NULL  
FROM RMD_ACLIST RA WITH (NOLOCK) 
JOIN RMD_ACLIST RC WITH (NOLOCK)  ON RA.PARENT = RC.ACID 
JOIN RMD_ACLIST RG WITH (NOLOCK)  ON RC.PARENT = RG.ACID
WHERE RG.TYPE = 'G' AND RG.PARENT IN ('PA')  AND RA.TYPE = 'A' AND RA.ACID   LIKE 'PA%' 

UNION ALL

SELECT RA.ACID,RG.ACNAME [A/C MAIN GROUP],RD.ACNAME,RC.ACNAME, NULL  
FROM RMD_ACLIST RA WITH (NOLOCK) 
JOIN RMD_ACLIST RC WITH (NOLOCK)  ON RA.PARENT = RC.ACID 
JOIN RMD_ACLIST RD WITH (NOLOCK)  ON RC.PARENT = RD.ACID
JOIN RMD_ACLIST RG WITH (NOLOCK)  ON RD.PARENT = RG.ACID
WHERE RG.TYPE = 'G' AND  RG.PARENT IN ('PA')  AND RA.TYPE = 'A' AND RA.ACID   LIKE 'PA%' 

UNION ALL

SELECT RA.ACID,RG.ACNAME [A/C MAIN GROUP],RE.ACNAME,RD.ACNAME,RC.ACNAME  
FROM RMD_ACLIST RA WITH (NOLOCK) 
JOIN RMD_ACLIST RC WITH (NOLOCK)  ON RA.PARENT = RC.ACID 
JOIN RMD_ACLIST RD WITH (NOLOCK)  ON RC.PARENT = RD.ACID
JOIN RMD_ACLIST RE WITH (NOLOCK)  ON RD.PARENT = RE.ACID
JOIN RMD_ACLIST RG WITH (NOLOCK)  ON RE.PARENT = RG.ACID
WHERE RG.TYPE = 'G' AND RG.PARENT IN ('PA')  AND RA.TYPE = 'A' AND RA.ACID   LIKE 'PA%' 
