CREATE OR ALTER  VIEW [dbo].[vwTrnProd_COGS] WITH SCHEMABINDING
AS
SELECT VCHRNO, VOUCHERTYPE, MCODE, BC, BATCH, SNO, COSTING_INVOICE, Quantity, CRATE, STAMP, ROW_VERSION, ORIGIN_ROW_VERSION FROM DBO.TRNPROD_COGS
UNION ALL
SELECT VCHRNO, VOUCHERTYPE, MCODE, BC, BATCH, SNO, COSTING_INVOICE, Quantity, CRATE, STAMP, ROW_VERSION, ORIGIN_ROW_VERSION FROM DBO.ABBPROD_COGS