CREATE OR ALTER VIEW vwVehicleBarcode
AS
SELECT BD.*, P.RATE VPRate, IIF(COALESCE(P.CRATE,0) =0, P.RATE, P.CRATE) VCRate FROM BARCODE_DETAIL BD LEFT JOIN 
(
	SELECT VCHRNO, MCODE, BC, RATE, CRATE FROM RMD_TRNPROD WHERE VOUCHERTYPE IN ('PI','OP','CN')
	UNION ALL
	SELECT VCHRNO, MCODE, BC, RATE, CRATE FROM GRNPROD
)P ON BD.VEHICLEPURCHASEVOUCHER = P.VCHRNO AND BD.MCODE = P.MCODE AND BD.BARCODE = P.BC