CREATE OR ALTER PROCEDURE [dbo].[RSP_STOCKREPORT_BATCHWISE] 
--DBCC DROPCLEANBUFFERS
--DBCC FREEPROCCACHE
--DECLARE
	@DATE1 DATETIME,
	@DATE2 DATETIME,
	@WAREHOUSE VARCHAR(100) ='%',
	@MENUCAT VARCHAR(100) ='%',
	@SUPPLIER_ACID VARCHAR(20)='%',
	@MGROUP VARCHAR(20) = '%',
	@PTYPE INT='100',
	@PATH NVARCHAR(4000)='%',
	@MCODE varchar(25) = '%',
	@DIVISION VARCHAR(3)= '%',
	@OPT_RepMode tinyint = 0,					--All:0,NonZero:1,NegativeOnly:2,ZeroOnly:3
	@GROUP VARCHAR(25)='MI',
	@FYID VARCHAR(20) = '%'
AS

--SET @DATE1 = '2024-07-16'; SET @DATE2 ='2025-07-15';
--SET @FYID = '81/82'; --SET @ITEMCODE = 'M5374'
set nocount on

--DECLARE @SHOWBARCODEDETAIL TINYINT
DECLARE @IGNOREMINUSTK TINYINT
--DECLARE @BCWISERATE TINYINT
SELECT @IGNOREMINUSTK = IGNOREMINUSSTKINSVALUATION FROM SETTING

--GETTING WAREHOUSE LIST
-------------------------
IF OBJECT_ID('TEMPDB..#tblWarehouse') is not NULL drop table #tblWarehouse

CREATE TABLE #tblWarehouse (item varchar(100) COLLATE DATABASE_DEFAULT)
INSERT INTO #tblWarehouse SELECT ITEMS FROM DBO.Split(@WAREHOUSE ,',')


IF OBJECT_ID('TEMPDB..#RMD_TRNPROD') IS NOT NULL DROP TABLE #RMD_TRNPROD
--IF OBJECT_ID('TEMPDB..#DATA') IS NOT NULL DROP TABLE #DATA

SELECT 'OP100' VCHRNO,A.DIVISION,A.MCODE,A.BATCH,SUM(REALQTY) REALQTY,
SUM(REALQTY_IN) REALQTY_IN,WAREHOUSE,A.VoucherType INTO #RMD_TRNPROD FROM RMD_TRNPROD A 
INNER JOIN RMD_TRNMAIN B ON A.VCHRNO=B.VCHRNO AND A.DIVISION =B.DIVISION AND A.PhiscalID=B.PhiscalID 
WHERE ISNULL(A.PHISCALID,'') = @FYID AND (B.TRNDATE < @DATE1 OR A.VCHRNO LIKE 'OP%') AND B.DIVISION LIKE @DIVISION AND
(A.WAREHOUSE LIKE @WAREHOUSE OR A.WAREHOUSE IN (SELECT ITEM FROM #tblWarehouse)) AND ISNULL(A.MCODE,'') LIKE @MCODE 
GROUP BY A.DIVISION,A.MCODE,A.WAREHOUSE,A.BATCH, A.VoucherType

UNION ALL

SELECT A.VCHRNO VCHRNO,A.DIVISION,A.MCODE,A.BATCH,REALQTY,
REALQTY_IN,WAREHOUSE, A.VoucherType FROM RMD_TRNPROD A 
INNER JOIN RMD_TRNMAIN B ON A.VCHRNO=B.VCHRNO AND A.DIVISION =B.DIVISION AND A.PhiscalID=B.PhiscalID 
WHERE ISNULL(A.PHISCALID,'') = @FYID AND B.TRNDATE BETWEEN @DATE1 AND @DATE2 AND A.VCHRNO NOT LIKE 'OP%' AND B.DIVISION LIKE @DIVISION
AND (A.WAREHOUSE LIKE @WAREHOUSE OR A.WAREHOUSE IN (SELECT ITEM FROM #tblWarehouse)) AND ISNULL(A.MCODE,'') LIKE @MCODE 

--GETTING ITEM WISE STOCK BALANCE RECORD WITH STOCK VALUE
---------------------------------------------------------
IF OBJECT_ID('TEMPDB..#RMD_TRNPROD1') IS NOT NULL DROP TABLE #RMD_TRNPROD1

SELECT * INTO #RMD_TRNPROD1 FROM
(
	SELECT A.MCODE,A.BATCH, B.MFGDATE, B.EXPDATE, A.OPQTY,A.INQTY,A.OUTQTY,A.STOCKBALANCE,
	B.SRATE,
	PRATE = IIF(@IGNOREMINUSTK = 1 AND A.STOCKBALANCE<0, 0 , B.PRATE), 
	STOCKVALUE= IIF(@IGNOREMINUSTK = 1 AND A.STOCKBALANCE<0, 0 , B.PRATE) * A.STOCKBALANCE
	FROM 
	(
		SELECT MCODE, BATCH,
		OPQTY = SUM(IIF(VoucherType IN ('OP'), REALQTY_IN-RealQty, 0)),
		INQTY = SUM(IIF(REALQTY_IN > 0, REALQTY_IN, 0)) ,
		OUTQTY= SUM(IIF(REALQTY_IN > 0, 0, RealQty)),
		STOCKBALANCE=SUM(REALQTY_IN)-SUM(REALQTY)
		FROM #RMD_TRNPROD A GROUP BY A.MCODE, A.BATCH, A.DIVISION
	) A 
	LEFT JOIN 
	(
		SELECT MCODE, BATCHCODE, MFGDATE, EXPDATE, IIF(COALESCE(LandingCost,0) = 0, CostPrice,LandingCost) PRATE, SELLRATEBEFORETAX SRATE FROM BATCHPRICE_MASTER
	) B ON A.MCODE = B.MCODE AND A.BATCH = B.BATCHCODE
)A WHERE ((@OPT_RepMode = 1 AND STOCKBALANCE <> 0) OR (@OPT_RepMode = 2 AND STOCKBALANCE < 0) OR (@OPT_RepMode = 3 AND STOCKBALANCE = 0) OR  (@OPT_RepMode = 0 AND STOCKBALANCE < 1000000000)) 


--PREPARING RECORD TO SHOW REPORT AS PER REPORT OPTION
--------------------------------------------------------
if object_id('tempdb..#TRNPROD1') IS NOT NULL DROP TABLE #TRNPROD1

CREATE TABLE #TRNPROD1 (ITEMCODE VARCHAR(25) COLLATE DATABASE_DEFAULT,DESCA VARCHAR(200) COLLATE DATABASE_DEFAULT,BATCH VARCHAR(50) COLLATE DATABASE_DEFAULT,
MFGDATE DATE, EXPDATE DATE, BASEUNIT VARCHAR(50), OPQTY NUMERIC(18,4),INQTY NUMERIC(18,4),OUTQTY NUMERIC(18,4), STOCKBALANCE NUMERIC(18,4),PRATE NUMERIC(18,4),
STOCKVALUE NUMERIC(18,4),SRATE NUMERIC(18,4),SUPPLIER VARCHAR(100) COLLATE DATABASE_DEFAULT,MCODE VARCHAR(100) COLLATE DATABASE_DEFAULT)


if object_id('tempdb..#TRNPROD') IS NOT NULL DROP TABLE #TRNPROD
SELECT * INTO #TRNPROD FROM 
(
	SELECT B.DESCA, B.MENUCODE ITEMCODE, BATCH, A.MFGDATE, A.EXPDATE, B.BASEUNIT,  D.ACNAME SUPPLIER, A.MCODE, A.PRATE, A.SRATE,
	OPQTY,INQTY,OUTQTY,STOCKBALANCE,STOCKVALUE
	FROM #RMD_TRNPROD1 A INNER JOIN MENUITEM B ON A.MCODE= B.MCODE 	
	LEFT JOIN RMD_ACLIST D ON ISNULL(B.SUPCODE,'') = D.ACID
	WHERE ISNULL(B.MCAT,'') LIKE @MENUCAT AND ISNULL(B.MGROUP,'') LIKE @MGROUP AND ISNULL(B.SUPCODE,'') LIKE @SUPPLIER_ACID AND
	((@PATH='%' AND ISNULL(B.PATH,'') LIKE @PATH) OR (@PATH <> '%' 
	AND B.PARENT IN (SELECT MCODE FROM DBO.TreeExpand_function(@PATH,'PATH','1'))))
	AND ((@PTYPE=100 AND ISNULL(B.PTYPE,0)<10) OR (@PTYPE <> 100 AND ISNULL(B.PTYPE,0) = @PTYPE))
)A

INSERT INTO #TRNPROD1(ITEMCODE,DESCA,BATCH, MFGDATE, EXPDATE, BASEUNIT,OPQTY,INQTY,OUTQTY,STOCKBALANCE,PRATE,STOCKVALUE,SRATE,SUPPLIER,MCODE)
SELECT * FROM
(
	SELECT ITEMCODE,DESCA,BATCH,MFGDATE,EXPDATE,BASEUNIT,
	SUM(OPQTY) OPQTY,SUM(INQTY) PQTY,SUM(OUTQTY) TRANSFERIN, SUM(STOCKBALANCE) STOCKBALANCE,
	ISNULL(A.PRATE,0) PRATE,SUM(STOCKVALUE) STOCKVALUE,A.SRATE,A.SUPPLIER,A.MCODE
	FROM #TRNPROD A GROUP BY A.ITEMCODE,A.DESCA,A.BATCH,A.MFGDATE,A.EXPDATE,A.BASEUNIT,ISNULL(A.PRATE,0),A.SRATE,A.SUPPLIER,A.MCODE
) A
	
 
--PREPARING REPORT 
-------------------
--CREATING TEMPORTY TABLE TO HOLD THE REPORT OUTPUT
----------------------------------------------------
IF OBJECT_ID('TEMPDB..#RESULT') IS NOT NULL DROP TABLE #RESULT
SELECT H.[Main Group], H.[Main Category], H.[Sub Category], H.[Super Category], ITEMCODE, A.DESCA, BATCH, MFGDATE,EXPDATE,  BASEUNIT,
SUM(OPQTY) OPQTY,SUM(INQTY) INQTY, SUM(OUTQTY) OUTQTY,
SUM(STOCKBALANCE) STOCKBALANCE, CONVERT(DECIMAL(18,2), PRATE) PRATE,CONVERT(DECIMAL(18,2), SUM(STOCKVALUE)) STOCKVALUE,CONVERT(DECIMAL(18,2), A.SRATE) SRATE,A.SUPPLIER,A.MCODE
INTO #RESULT
FROM #TRNPROD1 A 
JOIN vwItemHeirarchy H ON A.MCODE = H.MCODE
GROUP BY H.[Main Group], H.[Main Category], H.[Sub Category], H.[Super Category],A.ITEMCODE,A.DESCA,A.BATCH,A.MFGDATE,A.EXPDATE,A.BASEUNIT,A.PRATE,A.SRATE,A.SUPPLIER,A.MCODE
ORDER BY A.DESCA

SELECT * FROM #RESULT

--IF OBJECT_ID('TEMPDB..#RESULT') IS NOT NULL DROP TABLE #RESULT
if object_id('tempdb..#TRNPROD1') IS NOT NULL DROP TABLE #TRNPROD1
if object_id('tempdb..#TRNPROD') IS NOT NULL DROP TABLE #TRNPROD
IF OBJECT_ID('TEMPDB..#RMD_TRNPROD') IS NOT NULL DROP TABLE #RMD_TRNPROD
IF OBJECT_ID('TEMPDB..#tblWarehouse') is not NULL drop table #tblWarehouse