IF OBJECT_ID('TRIGGER_PREVENT_CHANGE_ON_PREMAIN') IS NOT NULL
DROP TRIGGER TRIGGER_PREVENT_CHANGE_ON_PREMAIN 

IF OBJECT_ID('TRIGGER_PREVENT_CHANGE_ON_PREPROD') IS NOT NULL
DROP TRIGGER TRIGGER_PREVENT_CHANGE_ON_PREPROD