CREATE OR ALTER FUNCTION fnProductFilter(@ITEMLIST VARCHAR(1000) ='', @MCAT VARCHAR(50) = '%', @MCAT1 VARCHAR(50) = '%', @MGROUP VARCHAR(25) = '%', @PTYPE INT =100, @SUPCODE VARCHAR(25) = '%', @FP1 BIT  = 0, @FP2 BIT  = 0, @FP3 BIT  = 0, @FP4 BIT  = 0, @FP5 BIT  = 0, @FP6 BIT  = 0)
RETURNS TABLE
AS 
RETURN
(
	SELECT M.* FROM MENUITEM M LEFT JOIN 
	(
		SELECT * FROM DBO.Split(@ITEMLIST,',')
	) L ON M.MCODE = L.items
	WHERE (COALESCE(@ITEMLIST,'') = '' OR L.items IS NOT NULL) AND MCAT LIKE @MCAT AND MGROUP LIKE @MGROUP AND SUPCODE LIKE @SUPCODE AND (@PTYPE = 100 OR PTYPE = @PTYPE)
)