CREATE OR ALTER PROCEDURE [dbo].[RSP_STOCKLEDGER]
--declare
@MCODE VARCHAR(20) = '%',
@SELECTEDITEMLIST VARCHAR(500) = '',
@WAREHOUSE VARCHAR(100), 
@DATE1 SMALLDATETIME,
@DATE2 SMALLDATETIME,
@DIVISION VARCHAR(3) = '%',
@InSingleLedger BIT = 0,
@FYID VARCHAR(10) = '%',
@BYBARCODE tinyint =0,
@CHK_GRNWise TINYINT = 0                     --CHK_GRNWise:1:0	  
AS

--SELECT @MCODE='M18596', @WAREHOUSE='%', @DATE1='2023-07-16', @DATE2='2024-07-16', @BYBARCODE=1, /* @SELECTEDITEMLIST='m100,M175',*/ @FYID = '80/81', @DIVISION = 'NSC', @WAREHOUSE = 'Central Warehouse'

DECLARE @RATEMODE TINYINT
SELECT @RATEMODE = enableratediscount FROM SETTING

IF ISNULL(@SELECTEDITEMLIST,'') <> ''
SET @MCODE = @SELECTEDITEMLIST

IF OBJECT_ID('TEMPDB..#RESULTTABLE') IS NOT NULL DROP TABLE #RESULTTABLE

IF OBJECT_ID('TEMPDB..#BARCODEDETAIL') IS NOT NULL DROP TABLE #BARCODEDETAIL


DECLARE @ItemLookup TABLE (MCODE VARCHAR(25), DESCA VARCHAR(100), BASEUNIT VARCHAR(25))

	IF @InSingleLedger = 1
	INSERT INTO @ItemLookup VALUES ('M','ITEMS','')

		INSERT INTO @ItemLookup
		SELECT MCODE, DESCA, BASEUNIT FROM MENUITEM WHERE MCODE IN (select * from dbo.Split(@MCODE,','))


		SELECT * INTO #BARCODEDETAIL from BARCODE_DETAIL where mcode in (select * from dbo.Split(@MCODE,','))

		 
SELECT * INTO #RESULTTABLE FROM 
(
	SELECT MCODE, NULL AS TRNDATE,NULL AS TRNTIME, NULL AS BSDATE, NULL AS VCHRNO,NULL AS CHALANNO,'OPENING STOCK' AS PARTYNAME,NULL AS VATNO,NULL AS UNIT,NULL AS BILLQTY, NULL AS BUNIT,NULL AS RATE,
	CASE WHEN (OPBAL >0) THEN OPBAL ELSE NULL END AS REALQTY_IN,
	CASE WHEN(OPBAL <0) THEN ABS(OPBAL) ELSE NULL END AS REALQTY, 
	OPBAL as bal,NULL AS REMARKS,NULL AS TERMINAL,null as division, NULL BC,NULL COLOR,NULL SIZE, 1 SNO FROM 
	(
		SELECT IIF(@InSingleLedger = 1, 'M', a.MCODE) MCODE, SUM(REALQTY_IN)-SUM(REALQTY) AS OPBAL FROM RMD_TRNPROD A 
		INNER JOIN RMD_TRNMAIN B WITH (NOLOCK) ON A.VCHRNO=B.VCHRNO 
		INNER JOIN RMD_WAREHOUSE Z ON A.WAREHOUSE = Z.NAME  
		WHERE (TRNDATE < @DATE1 OR LEFT(A.VCHRNO,2) ='OP') AND A.WAREHOUSE LIKE @WAREHOUSE AND A.DIVISION LIKE @DIVISION AND Z.ISADJUSTMENT = 0 AND MCODE IN (select * from dbo.Split(@MCODE,',')) AND A.PHISCALID = @FYID
		GROUP BY IIF(@InSingleLedger = 1, 'M', a.MCODE)
	) B
	UNION ALL
	SELECT Z.MCODE, TRNDATE, TRNTIME, BSDATE, VCHRNO, CHALANNO, PARTYNAME, VATNO, UNIT, QUANTITY, C.BASEUNIT, RATE, REALQTY_IN, REALQTY_OUT, BAL, REMARKS, TERMINAL, DIVISION,  BC,COLOR,SIZE, 2 SNO	FROM
	(
		SELECT IIF(@InSingleLedger = 1, 'M', N.MCODE) MCODE, M.TRNDATE, M.TRNTIME, M.BSDATE, M.VCHRNO,M.CHALANNO,M.PARTYNAME,VATNO,UNIT,
		CASE WHEN LEFT(M.VCHRNO,2) IN ('PI') THEN CASE WHEN ISNULL(N.CRATE,0) <> 0 THEN ISNULL(N.CRATE,0) ELSE N.REALRATE END ELSE N.REALRATE END AS RATE,
		CASE WHEN(REALQTY_IN=0) THEN null ELSE realqty_in END AS REALQTY_IN,
		CASE WHEN(REALQTY=0) THEN NULL ELSE REALQTY END REALQTY_OUT,
		null as bal,M.REMARKS,M.TERMINAL,m.division,N.BC,BD.COLOR,BD.SIZE,N.QUANTITY FROM 
		(
			SELECT A.VCHRNO,DIVISION,CHALANNO,TRNDATE, TRNTIME,BSDATE,TRNUSER,TERMINAL,PARTY,A.REMARKS,
			CASE WHEN (LEFT(VCHRNO,2)='IS') THEN 'STOCK ISSUE' 
				 WHEN (LEFT(VCHRNO,2)='SA') THEN 'STOCK ADJUSTMENT' 
				 WHEN (LEFT(VCHRNO,2)='SR') THEN 'SALES RETURN' 
				 WHEN (LEFT(VCHRNO,2)='PR') THEN 'PURCHASE RETURN'
				 WHEN (LEFT(VCHRNO,2)='PD') THEN 'PRODUCTION ENTRY'
				 WHEN (LEFT(VCHRNO,2)='DA') THEN 'DISASSEMBLY ENTRY'
				 WHEN (LEFT(VCHRNO,2)='DM') THEN 'STOCK SETTLEMENT - ' + UPPER(TRNMODE) 
				 WHEN (LEFT(VCHRNO,2)='TO') THEN 'BRANCH OUT - ' + D1.[NAME]
				 WHEN (LEFT(VCHRNO,2)='TR') THEN 'BRANCH IN - ' + D2.[NAME]
				 WHEN (LEFT(VCHRNO,2) IN ('TI','SI')) THEN IIF(ISNULL(A.BILLTO,'') = '', 'SALES INVOICE', A.BILLTO)
				 WHEN (LEFT(VCHRNO,2)='SI') THEN A.BILLTO ELSE
			B.ACNAME END  AS PARTYNAME,VATNO FROM 
			(
				SELECT VCHRNO, DIVISION, 
				CASE WHEN @RATEMODE = 1 AND VCHRNO LIKE 'TI%' THEN REFBILL ELSE CHALANNO END CHALANNO, 
				TRNDATE, BSDATE, TRNTIME,TRNUSER, TERMINAL, REMARKS,TRNMODE,
				CASE WHEN (PARAC IS NULL AND TRNAC IS NOT NULL) THEN TRNAC ELSE 
					CASE WHEN ((PARAC IS NULL AND TRNAC IS NULL)) THEN 'AT01002' ELSE PARAC END 
				END AS PARTY,BILLTO, BILLTOADD FROM RMD_TRNMAIN 
				WHERE PHISCALID = @FYID AND TRNDATE >=@DATE1 AND TRNDATE <= @DATE2 AND DIVISION LIKE @DIVISION
			) A 
			LEFT JOIN RMD_ACLIST B ON A.PARTY=B.ACID 
			LEFT JOIN DIVISION D1 ON A.BILLTO = D1.INITIAL
			LEFT JOIN DIVISION D2 ON A.BILLTOADD = D2.INITIAL
		) M 
		INNER JOIN RMD_TRNPROD N ON M.VCHRNO=N.VCHRNO
		LEFT JOIN #BARCODEDETAIL BD ON N.BC=BD.BARCODE AND N.MCODE=BD.MCODE
		INNER JOIN RMD_WAREHOUSE Z ON Z.NAME = N.WAREHOUSE 
		WHERE N.MCODE IN (select * from dbo.Split(@MCODE,',')) AND 
		WAREHOUSE LIKE @WAREHOUSE  AND Z.ISADJUSTMENT = 0 AND LEFT (M.VCHRNO,2) <> 'OP' AND N.PHISCALID = @FYID
	) AS Z, @ItemLookup C WHERE Z.MCODE = C.MCODE
) A order by A.trndate, CONVERT(DATETIME, A.TRNTIME)
--select * from #resulttable

SELECT DISTINCT A.MCODE, NULL TRNDATE,NULL TRNTIME, NULL MITI, '' VCHRNO,NULL CHALANNO,'Item : ' + M.DESCA PARTICULAR,NULL VATNO,
NULL UNIT,NULL RATE,NULL INQTY,NULL OUTQTY,NULL BALANCE,
NULL REMARKS,NULL TERMINAL,NULL DIVISION,NULL BC,NULL COLOR,NULL SIZE,'' ORD, 2 SNO
FROM #RESULTTABLE A JOIN MENUITEM M ON A.MCODE = M.MCODE
UNION ALL
SELECT MCODE,TRNDATE,TRNTIME,BSDATE,VCHRNO,CHALANNO,PARTYNAME,VATNO,
BUNIT, CONVERT(DECIMAL(18,2), RATE), CONVERT(DECIMAL(18,2), REALQTY_IN) , CONVERT(DECIMAL(18,2), REALQTY) , CONVERT(DECIMAL(18,2), SUM(ISNULL(REALQTY_IN,0)-ISNULL(REALQTY,0)) OVER(ORDER BY TRNDATE,CONVERT(DATETIME, TRNTIME), VCHRNO RANGE UNBOUNDED PRECEDING)) BALANCE,
REMARKS,TERMINAL,DIVISION,IIF(@BYBARCODE=1,BC,'')BARCODE,IIF(@BYBARCODE=1,COLOR,'')COLOR,IIF(@BYBARCODE=1,SIZE,'')SIZE,'A' ORD, SNO
FROM #RESULTTABLE 
UNION ALL
SELECT MCODE, NULL TRNDATE,NULL TRNTIME, NULL BSDATE,NULL VCHRNO,NULL CHALANNO,'TOTAL' PARTYNAME,NULL VATNO,
NULL UNIT,NULL RATE,SUM(REALQTY_IN),SUM(REALQTY),SUM(REALQTY_IN)-SUM(REALQTY) BALANCE,
NULL,NULL,NULL,NULL,NULL,NULL ,'B' ORD, 2 SNO
FROM #RESULTTABLE 
GROUP BY MCODE 
UNION ALL
SELECT DISTINCT MCODE, NULL TRNDATE,NULL TRNTIME,NULL BSDATE,NULL VCHRNO,NULL CHALANNO,'' PARTYNAME,NULL VATNO,
NULL UNIT,NULL RATE,NULL REALQTY_IN,NULL REALQTY,NULL BALANCE,
NULL,NULL,NULL,NULL,NULL,NULL,'C' ORD, 2 SNO
FROM #RESULTTABLE
UNION ALL
SELECT 'Z' MCODE, NULL TRNDATE,NULL TRNTIME,NULL BSDATE,NULL VCHRNO,NULL CHALANNO,'GRAND TOTAL' PARTYNAME,NULL VATNO,
NULL UNIT,NULL RATE,SUM(REALQTY_IN),SUM(REALQTY),SUM(REALQTY_IN)-SUM(REALQTY) BALANCE,
NULL,NULL,NULL,NULL,NULL,NULL,'D' ORD, 2 SNO
FROM #RESULTTABLE 
ORDER BY MCODE, ORD, SNO