CREATE OR ALTER PROC[dbo].[RSP_DAYENDREPORT]
--Declare
@DAYSTARTID int='',
@DIVISION  varchar(20)='',
@PHISCALID  varchar(20)=''
AS
select A.DAYSTARTID,B.SessionID,TerminalID,c.NAME TERMINAL,UserID,ComputerID,SessionStartDate,SessionEndDate,
CAST(D.TOTAMNT AS decimal(20,2)) TOTAMNT, CAST(D.DCAMNT AS decimal(20,2)) DCAMNT, CAST(D.VATAMNT AS decimal(20,2)) VATAMNT, 
CAST(D.NETAMNT AS decimal(20,2)) NETAMNT, CAST(D.NONTAXABLE AS decimal(20,2)) NONTAXABLE, CAST(D.TAXABLE AS decimal(20,2)) TAXABLE, 
CAST(ISNULL(E.AMOUNT, 0) AS decimal(20,2)) AS COUNTERAMOUNT, FB.FoodSales, FB.BeverageSales, FB.OtherSales, D.BILLS, D.[RETURN_BILLS], CAST(D.PAX AS INT) PAX
,CAST(D.TOTALSALES AS decimal(20,2)) TOTALSALES,CAST(D.TOTALRETURN AS decimal(20,2)) TOTALRETURN, CAST(ISNULL(P.AMOUNT,0) AS decimal(20,2)) PAYOUTAMOUNT,  CAST(ISNULL(Q.AMOUNT,0) AS decimal(20,2)) CASHDROPAMOUNT,CAST(ISNULL(Z.AMOUNT,0) AS decimal(20,2)) ReceivedAmount
From days A inner join Session B ON A.DAYSTARTID=B.DAYSTARTID AND A.DIVISION=B.Division AND A.PhiscalID=B.PhiscalID 
left join SALESTERMINAL c on b.TerminalID=c.INITIAL
INNER JOIN 
( 
	SELECT SHIFT SESSIONID,DIVISION,PhiscalID ,
	SUM(CASE WHEN VoucherType = 'CN' THEN -1 * TOTAMNT ELSE TOTAMNT END) TOTAMNT,
	SUM((CASE WHEN VoucherType = 'CN' THEN -1 * DCAMNT ELSE DCAMNT END)) DCAMNT,
	SUM((CASE WHEN VoucherType = 'CN' THEN -1 * VATAMNT ELSE VATAMNT END)) VATAMNT,
	SUM((CASE WHEN VoucherType = 'CN' THEN -1 * NETAMNT ELSE NETAMNT END)) NETAMNT,
	SUM((CASE WHEN VoucherType = 'CN' THEN -1 * TAXABLE ELSE TAXABLE END)) TAXABLE,
	SUM((CASE WHEN VoucherType = 'CN' THEN -1 * NONTAXABLE ELSE NONTAXABLE END)) NONTAXABLE, 
	SUM(BILLS) BILLS, SUM([RETURNS]) RETURN_BILLS, SUM(PAX) PAX,
	SUM(IIF(VoucherType = 'CN',0, NETAMNT)) TOTALSALES,
	SUM(IIF(VoucherType != 'CN',0, NETAMNT)) TOTALRETURN FROM 
	(
		SELECT VoucherType, SHIFT,TOTAMNT,DCAMNT,VATAMNT,NETAMNT,TAXABLE,NONTAXABLE,DIVISION,PhiscalID, 1 BILLS, 0 [RETURNS], Customer_Count PAX  FROM ABBMAIN 
		UNION ALL 
		SELECT VoucherType, SHIFT,TOTAMNT,DCAMNT,VATAMNT,NETAMNT,TAXABLE,NONTAXABLE,DIVISION,PhiscalID, CASE WHEN VoucherType = 'CN' THEN 0 ELSE 1 END
		, CASE WHEN VoucherType = 'CN' THEN 1 ELSE 0 END, IIF(VoucherType = 'CN',0, Customer_Count) PAX  FROM TRNMAIN 
	)
	AS A GROUP BY SHIFT,DIVISION,PhiscalID 
) as D ON B.SessionID=D.SESSIONID AND B.Division=D.DIVISION AND B.PhiscalID =D.PhiscalID 
LEFT JOIN
(
	SELECT TM.SHIFT, CONVERT(DECIMAL(18,2), SUM((CASE WHEN M.MCAT1 = 'FOOD' THEN P.TAXABLE + P.NONTAXABLE + P.VAT ELSE 0  END) 
	* (CASE WHEN TM.VoucherType = 'CN' THEN -1 ELSE 1 END))) FoodSales,
	CONVERT(DECIMAL(18,2), SUM((CASE WHEN  M.MCAT1 = 'BEVERAGE' THEN P.TAXABLE + P.NONTAXABLE + P.VAT ELSE 0  END) 
	* (CASE WHEN TM.VoucherType = 'CN' THEN -1 ELSE 1 END))) BeverageSales,
	CONVERT(DECIMAL(18,2), SUM((CASE WHEN  M.MCAT1 NOT IN ('BEVERAGE', 'FOOD') THEN P.TAXABLE + P.NONTAXABLE + P.VAT ELSE 0  END) 
	* (CASE WHEN TM.VoucherType = 'CN' THEN -1 ELSE 1 END))) OtherSales
	FROM [days] A inner join Session B ON A.DAYSTARTID=B.DAYSTARTID AND A.DIVISION=B.Division AND A.PhiscalID=B.PhiscalID 
	JOIN SALES_TRNMAIN TM ON TM.SHIFT = B.SessionID
	JOIN SALES_TRNPROD P ON TM.VCHRNO = P.VCHRNO 
	JOIN MENUITEM M ON P.MCODE = M.MCODE
	WHERE A.DAYSTARTID = @DAYSTARTID AND TM.VoucherType IN ('SI','TI','CN')
	GROUP BY TM.SHIFT
) FB ON FB.SHIFT = D.SESSIONID
LEFT JOIN 
(
	SELECT SESSIONID,DIVISION,PhiscalID,SUM(AMOUNT) AMOUNT FROM tblDenomination GROUP BY SESSIONID,DIVISION,PhiscalID
)  AS E ON B.SessionID = E.SESSIONID AND B.Division=E.DIVISION AND B.PhiscalID=E.PhiscalID 
LEFT JOIN
(
	SELECT SUM(AMOUNT) AMOUNT,DIVISION,SHIFTID,PHISCALID FROM CASHFLOWTRAN GROUP BY SHIFTID,DIVISION,PhiscalID
)P ON B.Division=P.division AND B.SessionID=P.SHIFTID AND B.PhiscalID=P.PhiscalID
LEFT JOIN 
(
	SELECT SUM(AMOUNT) AMOUNT,DIVISION,SHIFTID,PHISCALID FROM PARTIALSETTLEMENT GROUP BY SHIFTID,DIVISION,PhiscalID
) Q ON B.Division=Q.division AND B.SessionID=Q.SHIFTID AND B.PhiscalID=Q.PhiscalID
LEFT JOIN 
(
	SELECT SUM(AMOUNT) AMOUNT,ReceivedTerminal,PHISCALID,ReceivedShiftId FROM PARTIALSETTLEMENT where IsReceived = 1 GROUP BY ReceivedShiftId,
	ReceivedTerminal,PhiscalID 
) Z ON B.TerminalID=Z.ReceivedTerminal  AND B.PhiscalID=Z.PhiscalID AND B.SessionID=Z.ReceivedShiftId
WHERE A.DAYSTARTID= @DAYSTARTID AND A.DIVISION =@DIVISION AND A.PHISCALID = @PHISCALID