CREATE OR ALTER PROC [DBO].[RSP_PRODUCTION_CONSUMPTION_REPORT]
	--DECLARE
	@DATE1 DATETIME
	,@DATE2 DATETIME
	,@DIVISION VARCHAR(100) = '%'
	,@WAREHOUSE VARCHAR(1000) = '%'
	,@PRODUCTIONITEM VARCHAR(100) = '%'
AS
--SELECT @DATE1='2024-01-31 00:00:00' ,@DATE2='2024-01-31 00:00:00'
IF OBJECT_ID('TEMPDB..#DATA') IS NOT NULL
	DROP TABLE #DATA

IF OBJECT_ID('TEMPDB..#RESULT') IS NOT NULL
	DROP TABLE #RESULT

SELECT IM.VCHRNO
	,IM.TRNDATE
	,IM.BSDATE
	,IM.REFBILL
	,IVP.MCODE PRODUCTION_ITEM
	,IVP.RATE PDRATE
	,IVP.REALQTY_IN
	,IVP.UNIT
	,IVP.WAREHOUSE PD_WAREHOUSE
	,IVC.MCODE CONSUMPTION_ITEM
	,IVC.WAREHOUSE PC_WAREHOUSE
	,IVC.RATE CONS_RATE
	,IVC.RealQty
	,IVC.UNIT CONS_UNIT
	,IVC.REMARKS
	,ROW_NUMBER() OVER (
		PARTITION BY IM.VCHRNO
		,IVP.MCODE ORDER BY IM.VCHRNO
			,IM.TRNDATE
		) XNO
INTO #DATA
FROM INVMAIN IM
JOIN INVPROD IVP ON IM.VCHRNO = IVP.VCHRNO
	AND IVP.REALQTY_IN > 0
JOIN INVPROD IVC ON IVC.RealQty > 0
	AND IVC.VCHRNO = IM.VCHRNO
	AND (
		(ivp.mcode = ivc.MasterMCode)
		OR (
			IVC.MasterMCode IS NULL
			OR 1 = 1
			)
		)
WHERE IM.VoucherType = 'PD'
	AND IM.TRNDATE BETWEEN @DATE1
		AND @DATE2
	AND IM.DIVISION LIKE @DIVISION
	AND IVP.WAREHOUSE LIKE @WAREHOUSE
	AND IVP.MCODE LIKE @PRODUCTIONITEM

SELECT IIF(XNO = 1, CONVERT(VARCHAR(100), sn), '') SN
	,IIF(XNO = 1, VCHRNO, '') ENTRY_NO
	,IIF(XNO = 1, FORMAT(TRNDATE, 'dd-MM-yyyy'), '') DATE
	,IIF(XNO = 1, A.BSDATE, '') BSDATE
	,IIF(XNO = 1, A.REFBILL, '') REFNO
	,IIF(XNO = 1, DESCA, '') DESCA
	,IIF(XNO = 1, A.PD_WAREHOUSE, '') PD_WAREHOUSE
	,IIF(XNO = 1, CONVERT(VARCHAR(100), A.PDRATE), '') PDRATE
	,IIF(XNO = 1, CONVERT(VARCHAR(100), A.REALQTY_IN), '') PDQTY
	,IIF(XNO = 1, A.UNIT, '') PDUNIT
	,A.CONSUMPTION_ITEM
	,A.PC_WAREHOUSE
	,A.CONS_RATE
	,A.RealQty CON_QTY
	,A.CONS_UNIT
	,A.REMARKS
FROM (
	SELECT RWN.ROWN SN
		,A.VCHRNO
		,A.TRNDATE
		,A.BSDATE
		,A.REFBILL
		,PDM.DESCA
		,A.PD_WAREHOUSE
		,A.PDRATE
		,A.REALQTY_IN
		,A.UNIT
		,PDC.DESCA CONSUMPTION_ITEM
		,A.PC_WAREHOUSE
		,A.CONS_RATE
		,A.RealQty
		,A.CONS_UNIT
		,A.REMARKS
		,'A' FLG
		,A.XNO
	FROM #DATA A
	JOIN MENUITEM PDM ON PDM.MCODE = A.PRODUCTION_ITEM
	JOIN MENUITEM PDC ON PDC.MCODE = A.CONSUMPTION_ITEM
	JOIN	(	SELECT DISTINCT ROW_NUMBER() OVER (	ORDER BY VCHRNO) AS ROWN,VCHRNO FROM #DATA GROUP BY VCHRNO
				) RWN ON A.VCHRNO = RWN.VCHRNO
	
			UNION
	
			SELECT DISTINCT RWN.ROWN
				,A.VCHRNO ENTRY_NO
				,TRNDATE DATE
				,NULL BSDATE
				,NULL REFNO
				,NULL DESCA
				,NULL PD_WAREHOUSE
				,NULL PDRATE
				,NULL PDQTY
				,NULL PDUNIT
				,NULL CONSUMPTION_ITEM
				,NULL PC_WAREHOUSE
				,NULL CONS_RATE
				,NULL CON_QTY
				,NULL CONS_UNIT
				,NULL REMARKS
				,'ZZZZZZ' FLG
				,'999' XNO
			FROM #DATA A
			JOIN (
				SELECT DISTINCT ROW_NUMBER() OVER (
						ORDER BY VCHRNO
						) AS ROWN
					,VCHRNO
				FROM #DATA
				GROUP BY VCHRNO
				) RWN ON A.VCHRNO = RWN.VCHRNO
			) A
	ORDER BY VCHRNO
	,FLG
	,XNO
	,TRNDATE