CREATE OR ALTER PROCEDURE [dbo].[RSP_STOCKVARIANCEREPORT]
	@WAREHOUSE  VARCHAR(100)='%',
	@DATE1  DATETIME,
	@MGROUP  VARCHAR(100) = '%',
	@AdjustmentBatch  VARCHAR(100),
	@OPT_FLAG  TINYINT = 1,		--Difference:1,Excess:2,Shortage:3,Equal:4,NotInCount:5,All:6,PhysicalOnly:7
	@DATE2  DATETIME = GETDATE,
	@CHK_BYBARCODE tinyint = 0,	--ByBarcode:1:0
	--@OPT_STOCKCOUNTING TINYINT = 0,		--StockCounting:0,PurchaseCounting:1
	@FYID VARCHAR(10)
AS
		exec dbo.NSP_STOCKVARIANCEREPORT @WARE =@WAREHOUSE ,
			@DATE =@DATE2 ,
			@MGROUP =@MGROUP,
			@BATCH =@AdjustmentBatch ,
			@FLAG =@OPT_FLAG,
			@DATE1 =@DATE2,
			@BYBARCODE =@CHK_BYBARCODE,
			@FYID = @FYID
