CREATE OR ALTER   VIEW [dbo].[TRNMAIN_VIEW_SREPORT]
AS
SELECT A.VCHRNO, A.DIVISION,A.CHALANNO,A.TRNDATE,A.BSDATE,A.TRNTIME,TRNMODE,TRNAC, PARAC, B.ACNAME, REMARKS,TERMINAL,RECEIVEBY,MEMBERNO,ISNULL(B.VATNO,'') VATNO,ISNULL(RATETYPE,0) RATETYPE, 
CASE WHEN TRNMODE = 'CREDIT' THEN B.ACNAME ELSE A.BILLTO END CNAME, ISNULL(A.BILLTOTEL, '') BILLTOTEL,a.TOTALLOYALTY,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN TOTAMNT ELSE TOTAMNT *-1 END AS TOTAMNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN DCAMNT ELSE DCAMNT *-1 END AS DCAMNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN VATAMNT ELSE VATAMNT *-1 END AS VATAMNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN NETAMNT ELSE NETAMNT *-1 END AS NETAMNT,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN TAXABLE ELSE TAXABLE *-1 END AS TAXABLE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN NONTAXABLE ELSE NONTAXABLE *-1 END AS NONTAXABLE,
CASE WHEN LEFT(A.VCHRNO,2) IN ('SI','TI','IC') THEN STAX ELSE STAX *-1 END AS STAX
FROM RMD_TRNMAIN A LEFT JOIN RMD_ACLIST B
ON A.TRNAC = B.ACID WHERE LEFT(A.VCHRNO,2) IN ('SI','SR','TI','CN','IC','IR','NC','RE')