CREATE OR ALTER   PROC [dbo].[RSP_SALESFIGURE_PARTYWISE]
@DATE1 DATETIME,
@DATE2 DATETIME,
@DIVISION VARCHAR(3) = '%',
@OPT_PARTYTYPE TINYINT = 0,										--Customer:0,Supplier:1
@OPT_SHOWSUMMARY_REPORT TINYINT = 0,								--Summary:1,Detail:0
@CHK_TOPNSORT TINYINT = 0,										--TopNSort:1:0
@CUSTOMER VARCHAR(20) ='%',
@SUPPLIER_ACID VARCHAR(20) ='%',
@AMOUNT  NUMERIC(18,2) = 0,
@AREA_ID int=0,
@CATEGORY_ID int=0
AS
DECLARE @ACID VARCHAR(20)
IF @OPT_PARTYTYPE = 0
	SET @ACID = @CUSTOMER
ELSE 
	SET @ACID = @SUPPLIER_ACID
IF @OPT_SHOWSUMMARY_REPORT = 0
	EXEC SP_SALESFIGURE_PARTYWISE_DETAIL 
		@DATE1 = @DATE1,
		@DATE2=@DATE2,
		@ACID = @ACID, 
		@PTYPE = @OPT_PARTYTYPE,
		@TOPNSORT = @CHK_TOPNSORT,
		@DIV = @DIVISION
		,@AREA_ID  =@AREA_ID
	    ,@CATEGORY_ID =@CATEGORY_ID
ELSE 
	EXEC SP_SALESFIGURE_PARTYWISE_SUMMARY
		@DATE1 = @DATE1,
		@DATE2=@DATE2,
		@ACID = @ACID, 
		@PTYPE = @OPT_PARTYTYPE,
		@TOPNSORT = @CHK_TOPNSORT,
		@DIV = @DIVISION,
		@AMOUNT = @AMOUNT
	    ,@AREA_ID  =@AREA_ID
	    ,@CATEGORY_ID =@CATEGORY_ID

