CREATE OR ALTER PROCEDURE [dbo].[SP_SALESFIGURE_PARTYWISE_SUMMARY]
--DECLARE
    @RMODE AS TINYINT = 0,
	@DATE1 AS DATETIME,
	@DATE2 AS DATETIME,
	@ACID AS VARCHAR(25) = '%',
	@PTYPE AS TINYINT = 1,
	@TOPNSORT AS TINYINT,
	@DIV AS VARCHAR(10) = '%',
	@AMOUNT AS NUMERIC(18,2) = 0,
	@PARTYTYPE AS INT = -1,
	@AREA_ID INT = 0,
	@CATEGORY_ID INT = 0
AS
set nocount on
--SELECT @DATE1 = '2024-07-16', @DATE2 = '2025-07-15', @PTYPE = 0, @TOPNSORT = 0, @AREA_ID = 3

BEGIN
	IF OBJECT_ID('TEMPDB..#PARTYTYPE') is not null drop table #PARTYTYPE
	CREATE TABLE #PARTYTYPE (ID INT,PARTYTYPE VARCHAR(50))
	INSERT INTO #PARTYTYPE(ID,PARTYTYPE) VALUES(0,'General')
	INSERT INTO #PARTYTYPE(ID,PARTYTYPE) VALUES(1,'Distributor')
	INSERT INTO #PARTYTYPE(ID,PARTYTYPE) VALUES(2,'Whole Seller')
	INSERT INTO #PARTYTYPE(ID,PARTYTYPE) VALUES(3,'Retailer')
	INSERT INTO #PARTYTYPE(ID,PARTYTYPE) VALUES(4,'Flat Rated')
END

DROP TABLE IF EXISTS #PARTYFILTER
select * INTO #PARTYFILTER from fnPartyFilter(@AREA_ID,@CATEGORY_ID,@ACID,0,0,0,0,0)

--CUSTOMER WISE SUMMARY SALES FIGURE REPORT
IF @PTYPE= 0 	-- CUSTOMER WISE
	SELECT ROW_NUMBER() OVER (ORDER BY CASE WHEN @TOPNSORT = 1 THEN BILLAMNT END DESC,ACNAME) AS SNO, * FROM 
	(
		SELECT A.CNAME ACNAME,BILLTOTEL VATNO,B.PARTYTYPE,CONVERT(DECIMAL(18,2), SUM(TOTAMNT)) AS GROSS
		, CONVERT(DECIMAL(18,2), (SUM(TOTALLOYALTY)/SUM(TOTAMNT))*100) [LOYALTY DISCOUNT(%)]
		, CONVERT(DECIMAL(18,2), SUM(DCAMNT)) AS DISCOUNT
		, CONVERT(DECIMAL(18,2), SUM(TAXABLE) + SUM(NONTAXABLE)) AS NETSALE
		, CONVERT(DECIMAL(18,2), SUM(TAXABLE))AS TAXABLE
		, CONVERT(DECIMAL(18,2), SUM(NONTAXABLE)) AS NONTAXABLE
		, CONVERT(DECIMAL(18,2), SUM(VATAMNT)) AS VATAMNT
		, CONVERT(DECIMAL(18,2), SUM(NETAMNT)) AS BILLAMNT
		, ca.AREA_NAME,ca.CATEGORY_NAME
		FROM TRNMAIN_VIEW_SREPORT A 
		LEFT JOIN #PARTYTYPE B ON A.RATETYPE = B.ID
		LEFT JOIN #PARTYFILTER ca on ca.ACID = a.PARAC
		WHERE DIVISION LIKE @DIV 
			AND TRNDATE BETWEEN @DATE1 AND @DATE2 
			AND (TRNAC LIKE @ACID OR RECEIVEBY LIKE @ACID) 
			AND	LEFT(VCHRNO,2) IN ('SI','SR','TI','CN','RE') 
			AND ((@PARTYTYPE<0 AND A.RATETYPE>=0) OR (@PARTYTYPE>0 AND A.RATETYPE=@PARTYTYPE))
			AND (@AREA_ID = 0 OR CA.AREA_ID = @AREA_ID)
			AND (@CATEGORY_ID = 0 OR CA.CATEGORY_ID = @CATEGORY_ID)
			AND (@ACID = '%' OR CA.ACID = @ACID)
		GROUP BY CNAME,BILLTOTEL,B.PARTYTYPE,ca.AREA_NAME,ca.CATEGORY_NAME
		having SUM(TOTAMNT)<>0
	) A WHERE (@AMOUNT=0 AND ABS(NETSALE)>=@AMOUNT) OR (@AMOUNT<>0 AND NETSALE >=@AMOUNT) 
	ORDER BY CASE WHEN @TOPNSORT = 1 THEN BILLAMNT END DESC,ACNAME
ELSE
	--SUPPLIER WISE SUMMARY SALES FIGURE REPORT
	SELECT ROW_NUMBER() OVER (ORDER BY CASE WHEN @TOPNSORT = 1 THEN BILLAMNT END DESC,ACNAME) AS SNO, *
	FROM 
	(
		SELECT ISNULL(B.ACNAME,'UNKNOWN SUPPLIER') AS ACNAME,B.VATNO,NULL PTYPE
		, CONVERT(DECIMAL(18,2), SUM(AMOUNT)) AS GROSS 
		, CONVERT(DECIMAL(18,2), (SUM(TOTALLOYALTY)/SUM(TOTAMNT))*100) [LOYALTY DISCOUNT(%)]
		, CONVERT(DECIMAL(18,2), SUM(DISCOUNT)) AS DISCOUNT
		, CONVERT(DECIMAL(18,2), SUM(A.TAXABLE) + SUM(A.NONTAXABLE)) AS NETSALE
		, CONVERT(DECIMAL(18,2), SUM(A.TAXABLE)) AS TAXABLE
		, CONVERT(DECIMAL(18,2), SUM(A.NONTAXABLE)) AS NONTAXABLE
		, CONVERT(DECIMAL(18,2), SUM(VATAMNT)) AS VATAMNT
		, CONVERT(DECIMAL(18,2), SUM(NETAMOUNT)) AS BILLAMNT
		, B.ACID
		FROM TRNPROD_VIEW_SREPORT A INNER JOIN RMD_TRNMAIN C ON A.VCHRNO = C.VCHRNO
		LEFT JOIN RMD_ACLIST B ON A.SUPCODE = B.ACID 
		WHERE C.DIVISION LIKE @DIV 
			AND C.TRNDATE BETWEEN @DATE1 AND @DATE2 
			AND A.SUPCODE LIKE @ACID 
			AND	LEFT (A.VCHRNO,2) IN ('SI','SR','TI','CN','RE')
		GROUP BY B.ACNAME,B.ACID,B.VATNO
		HAVING SUM(AMOUNT)<>0
	) A WHERE (@AMOUNT=0 AND ABS(NETSALE)>=0) OR (@AMOUNT<>0 AND NETSALE >=@AMOUNT) 
	ORDER BY CASE WHEN @TOPNSORT = 1 THEN BILLAMNT END DESC,ACNAME
	


IF OBJECT_ID('TEMPDB..#PARTYTYPE') is not null drop table #PARTYTYPE

set nocount OFF

