CREATE OR ALTER     PROCEDURE [dbo].[SP_SALESFIGURE_PARTYWISE_DETAIL]
--DECLARE
    @RMODE AS TINYINT = 0,
	@DATE1 AS DATETIME,
	@DATE2 AS DATETIME,
	@ACID AS VARCHAR(25) = '%',
	@PTYPE AS TINYINT = 1,
	@TOPNSORT AS TINYINT,
	@DIV AS VARCHAR(10) = '%',
	@AREA_ID INT = 0,
	@CATEGORY_ID INT = 0

AS
--SET @DATE1 = '2022-07-17'; SET @DATE2 = '2024-07-15'

if OBJECT_ID('tempdb..#PARTYFILTER') is not null drop table #PARTYFILTER
select * INTO #PARTYFILTER from fnPartyFilter(@AREA_ID,@CATEGORY_ID,@ACID,0,0,0,0,0)

--CUSTOMER WISE SUMMARY SALES FIGURE REPORT
IF @PTYPE= 0 	-- CUSTOMER WISE
	SELECT ca.AREA_NAME,ca.CATEGORY_NAME, COALESCE(CP.CUSTNAME, CA.ACNAME) ACNAME, COALESCE(CA.VATNO, CP.PANNO) VATNO, A.MENUCODE, A.DESCA, A.QUANTITY, A.RATE, A.AMOUNT, A.[LOYALTY DISCOUNT(%)], A.DISCOUNT
	, A.NETSALE, A.TAXABLE, A.NONTAXBLE, A.VAT, A.BILLAMNT FROM 
	(
		SELECT B.PARAC, B.RECEIVEBY, MENUCODE, DESCA
		, CONVERT(DECIMAL(18,2), SUM(REALQTY) - SUM(REALQTY_IN)) AS QUANTITY
		, CONVERT(DECIMAL(18,2), RATE) RATE
		, CONVERT(DECIMAL(18,2),SUM(AMOUNT)) AS AMOUNT
		, CONVERT(DECIMAL(18,2), (SUM(A.LOYALTY)/SUM(AMOUNT))*100) [LOYALTY DISCOUNT(%)]
		, CONVERT(DECIMAL(18,2),SUM(DISCOUNT)) AS DISCOUNT
		, CONVERT(DECIMAL(18,2),SUM(A.TAXABLE+A.NONTAXABLE)) AS NETSALE
		, CONVERT(DECIMAL(18,2),SUM(A.TAXABLE)) AS TAXABLE
		, CONVERT(DECIMAL(18,2),SUM(A.NONTAXABLE)) AS NONTAXBLE
		, CONVERT(DECIMAL(18,2),SUM(VRATE)) AS VAT
		, CONVERT(DECIMAL(18,2),SUM(NETAMOUNT)) AS BILLAMNT
		, MCODE
		FROM TRNPROD_VIEW_SREPORT A INNER JOIN RMD_TRNMAIN B ON A.VCHRNO = B.VCHRNO AND A.DIVISION = B.DIVISION
		WHERE B.DIVISION LIKE @DIV 
			AND B.TRNDATE BETWEEN @DATE1 AND @DATE2 
			AND LEFT(A.VCHRNO,2) IN ('SI','SR','TI','CN','RE') 
			AND (ISNULL(B.PARAC,'') LIKE @ACID OR B.RECEIVEBY LIKE @ACID)
		GROUP BY MCODE,MENUCODE,DESCA,RATE, B.PARAC, B.RECEIVEBY
		HAVING SUM(A.AMOUNT) <> 0
	) A LEFT JOIN #PARTYFILTER ca on ca.ACID = A.PARAC
	LEFT JOIN vwCustomerProfile cp on CP.CUSTID = A.RECEIVEBY
	ORDER BY ACNAME, DESCA
ELSE
	SELECT ISNULL(AC.ACNAME,'UNKNOWN SUPPLIER') AS ACNAME, AC.VATNO, MENUCODE,DESCA
	, CONVERT(DECIMAL(18,2), SUM(REALQTY) - SUM(REALQTY_IN)) AS QUANTITY
	, CONVERT(DECIMAL(18,2), RATE) RATE
	, CONVERT(DECIMAL(18,2), SUM(AMOUNT)) AS AMOUNT
	, CONVERT(DECIMAL(18,2), (SUM(A.LOYALTY)/SUM(AMOUNT))*100) [LOYALTY DISCOUNT(%)]
	, CONVERT(DECIMAL(18,2), SUM(DISCOUNT)) AS DISCOUNT
	, CONVERT(DECIMAL(18,2), SUM(A.TAXABLE+A.NONTAXABLE)) AS NETSALE
	, CONVERT(DECIMAL(18,2), SUM(A.TAXABLE)) AS TAXABLE
	, CONVERT(DECIMAL(18,2), SUM(A.NONTAXABLE)) AS NONTAXBLE
	, CONVERT(DECIMAL(18,2), SUM(VRATE)) AS VAT
	, CONVERT(DECIMAL(18,2), SUM(NETAMOUNT)) AS BILLAMNT
	, MCODE
	FROM TRNPROD_VIEW_SREPORT A INNER JOIN RMD_TRNMAIN B ON A.VCHRNO = B.VCHRNO AND A.DIVISION = B.DIVISION
	LEFT Join RMD_ACLIST AC on AC.ACID = A.SUPCODE
	WHERE B.DIVISION LIKE @DIV 
		AND B.TRNDATE BETWEEN @DATE1 AND @DATE2 
		AND LEFT(A.VCHRNO,2) IN ('SI','SR','TI','CN','RE') 
		AND ISNULL(A.SUPCODE,'') LIKE @ACID
	GROUP BY MCODE,MENUCODE,DESCA,RATE, AC.ACNAME, AC.VATNO
	HAVING SUM(A.AMOUNT)<>0
	ORDER BY AC.ACNAME, DESCA



