CREATE OR ALTER     PROCEDURE [dbo].[RSP_DELIVERYREGISTER_REPORT]
--DECLARE 
	@DATE1 DATETIME,
	@DATE2 DATETIME,
	@PLEDGER_ACID VARCHAR(25)='%',
	@AGE NUMERIC(5,0) = 0,
	@OPT_BILLSTATUS TINYINT = 0,           --Billed:1,NotBilled:2,All:0
	@OPT_DTYPE VARCHAR(3) = '%',           --All:%,Delivery:DL%,DeliveryReturn:DR%
	@WAREHOUSE VARCHAR(25) = '%',
	@OPT_REPORT_TYPE TINYINT = 1,          --VoucherWise:1,CustomerWise:2,ItemWise:3,CustomerWiseSummary:4
	@MCODE VARCHAR(25) ='%',
	@PTYPE INT = 4
AS
BEGIN
DECLARE @VEHICLEDETAIL TINYINT
SELECT @VEHICLEDETAIL = HASVEHICLESALE FROM SETTING
IF @VEHICLEDETAIL = 0
	EXEC NSP_DELIVERYREGISTER_REPORT
		@DATE1 = @DATE1,
		@DATE2 =@DATE2,
		@ACID = @PLEDGER_ACID,
		@AGE = @AGE,
		@BILLED = @OPT_BILLSTATUS,
		@DType = @OPT_DTYPE,
		@WARE = @WAREHOUSE,
		@REPORT_TYPE = @OPT_REPORT_TYPE,
		@MC = @MCODE,
		@PTYPE = @PTYPE						
ELSE 
	EXEC NSP_DELIVERYREGISTER_REPORT_VEHICLEDETAILS
		@DATE1 = @DATE1,
		@DATE2 =@DATE2,
		@ACID = @PLEDGER_ACID,
		@AGE = @AGE,
		@BILLED = @OPT_BILLSTATUS,
		@DType = @OPT_DTYPE,
		@WARE = @WAREHOUSE,
		@REPORT_TYPE = @OPT_REPORT_TYPE,
		@MC = @MCODE,
		@PTYPE = @PTYPE				
END