CREATE OR ALTER   VIEW [dbo].[SyncCheckSum_FiscalYear]
AS
SELECT A.DIVISION Branch, A.PhiscalId, A.VoucherType TableName, MAX(ROW_VERSION) OVER () ROW_VERSION, NULL ORIGIN_ROW_VERSION, a.vchrCount RCount, 
'Line Items' AggName0, b.itemCount Agg0, 'Journal Count' AggName1, c.acTranCount Agg1, 'Total Qty' AggName2, b.totalQty Agg2, 'Gross Amount' AggName3, NETAMNT Agg3
, 'TAXABLE' AggName4, TAXABLE Agg4, 'NONTAXABLE' AggName5, NONTAXABLE Agg5, 'VATAMNT' AggName6, VATAMNT Agg6, 'Debit' AggName7, DRAMNT Agg7, 'Credit' AggName8, CRAMNT Agg8
FROM 
(
	SELECT MAX(ROW_VERSION) ROW_VERSION, COUNT(VOUCHERTYPE) vchrCount, SUM(NETAMNT) NETAMNT, SUM(TAXABLE) TAXABLE, SUM(NONTAXABLE) NONTAXABLE, SUM(VATAMNT) VATAMNT, VOUCHERTYPE, DIVISION, PHISCALID FROM RMD_TRNMAIN_SYNC  WITH (NOLOCK)
	WHERE TRNDATE < CONVERT(DATE, GETDATE())
	GROUP BY VOUCHERTYPE, DIVISION, PHISCALID
) A
LEFT JOIN 
(
	SELECT COUNT(A.VOUCHERTYPE) itemCount, SUM(Quantity) totalQty, A.VOUCHERTYPE, A.DIVISION, A.PHISCALID FROM RMD_TRNPROD A WITH (NOLOCK)
	JOIN RMD_TRNMAIN B  WITH (NOLOCK) ON A.VCHRNO = B.VCHRNO
	WHERE B.TRNDATE < CONVERT(DATE, GETDATE())
	GROUP BY A.VOUCHERTYPE, A.DIVISION, A.PHISCALID
) B ON A.VoucherType = B.VoucherType AND A.PhiscalID = B.PhiscalID AND A.DIVISION = B.DIVISION
LEFT JOIN 
(
	SELECT COUNT(A.VOUCHERTYPE) acTranCount, SUM(DRAMNT) DRAMNT, SUM(CRAMNT) CRAMNT, A.VOUCHERTYPE, A.DIVISION, A.PHISCALID FROM RMD_TRNTRAN A WITH (NOLOCK)
	JOIN RMD_TRNMAIN B  WITH (NOLOCK) ON A.VCHRNO = B.VCHRNO
	WHERE B.TRNDATE < CONVERT(DATE, GETDATE())
	GROUP BY A.VOUCHERTYPE, A.DIVISION, A.PHISCALID
)C ON A.VoucherType = C.VoucherType AND A.PhiscalID = C.PhiscalID AND A.DIVISION = C.DIVISION