IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRNMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE TRNMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ABBMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE ABBMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE PURMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE INVMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ACCMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE ACCMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OPMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE OPMAIN ADD ROW_VERSION ROWVERSION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AOPMAIN' AND COLUMN_NAME = 'ROW_VERSION')
ALTER TABLE AOPMAIN ADD ROW_VERSION ROWVERSION
