CREATE OR ALTER PROC OSP_GetItemAltUnits
--DECLARE
@MCODE VARCHAR(50),
@DIVISION VARCHAR(3),
@RateGroupId INT,
@RateGroupId_WSale INT = 0
AS
--SELECT @MCODE = 'M12797', @DIVISION = 'NSC', @RateGroupId = 0, @RateGroupId_WSale = 0
if @RateGroupId_WSale = 0
	SET @RateGroupId_WSale = @RateGroupId
--DECLARE @RateGroupId INT
--SELECT @RateGroupId = RateGroupID FROM DIVISION WHERE INITIAL = @DIVISION
DECLARE @AltRateByDiscount TINYINT
SELECT @AltRateByDiscount = EnableBatch FROM SETTING
SELECT A.MCODE, A.ALTUNIT, A.CONFACTOR, A.ISDEFAULT, A.ISDEFAULTPRATE, A.BRCODE, A.PRATE, 
COALESCE(C.RG_RATE, A.RATE) * A.CONFACTOR * CONVERT(NUMERIC(10,8), (1 - COALESCE(A.SRATE_DISCOUNT, 0)/100)) RATE, 
COALESCE(D.RG_RATE, A.RATE_B) * A.CONFACTOR * CONVERT(NUMERIC(10,8),(1 - COALESCE(A.WSRATE_DISCOUNT,0)/100)) RATE_B,
COALESCE(C.RG_DISCOUNT, 0) RG_DISCOUNT, COALESCE(D.RG_DISCOUNT, 0) RG_DISCOUNT_WSALE,
A.SRATE_DISCOUNT, A.WSRATE_DISCOUNT  FROM
(
	SELECT A.MCODE, A.BASEUNIT ALTUNIT, 1 CONFACTOR, 0 ISDEFAULT, 0 ISDEFAULTPRATE, NULL BRCODE, A.PRATE_A PRATE, A.RATE_A RATE, RATE_B, 0 SRATE_DISCOUNT, 0 WSRATE_DISCOUNT FROM MENUITEM A
	WHERE A.MCODE = @MCODE
	UNION ALL 
	SELECT A.MCODE, A.ALTUNIT, A.CONFACTOR, A.ISDEFAULT, A.ISDEFAULTPRATE, A.BRCODE, 
	CASE WHEN A.PRATE = 0 THEN M.PRATE_A * A.CONFACTOR ELSE A.PRATE END PRATE, 	
	CASE WHEN @AltRateByDiscount = 1 OR A.RATE = 0 THEN M.RATE_A  ELSE A.RATE/A.CONFACTOR END RATE, 
	M.RATE_B , A.SRATE_DISCOUNT, A.WSRATE_DISCOUNT 
	FROM MENUITEM M 
	JOIN MULTIALTUNIT A ON M.MCODE = A.MCODE WHERE M.MCODE = @MCODE  AND A.IsActive = 1 AND IsDiscontinue = 0
) A OUTER APPLY DBO.FNGETRATEGROUP(A.MCODE, A.RATE, @RateGroupId) C
OUTER APPLY DBO.FNGETRATEGROUP(A.MCODE, A.RATE_B, @RateGroupId_WSale) D