CREATE OR ALTER   PROC [dbo].[OSP_GetReceipeConsumptionList]
--DECLARE 
@Warehouse VARCHAR(25), 
@VCHRNO VARCHAR(25)
AS
--SET @VCHRNO ='TI1519-PKR-78/79'; SET @Warehouse = 'Main Warehouse'
DECLARE @ItemWiseWarehouse BIT
SELECT @ItemWiseWarehouse = ItemWiseWarehouse FROM SETTING
SELECT ISSUENO,REFSERIAL, MCODE , IsPrimaryItem,UNIT, ALTUNIT, REALQTY_IN, REALQTY_IN ALTQTY_IN, RealQty, RealQty AltQty, Quantity, RATE, RATE REALRATE, RATE ALTRATE,
RATE * Quantity AMOUNT, WAREHOUSE
FROM
(
	SELECT A.MCODE ISSUENO,  TR.RMCODE MCODE,TR.PMCODE PMCODE,TR.SNO REFSERIAL, TR.IsPrimaryItem, C.BASEUNIT UNIT, C.BASEUNIT ALTUNIT, 
	S.REALQTY_IN * TR.QTY / A.FACTOR REALQTY_IN,
	S.RealQty * TR.QTY / A.FACTOR RealQty,
	S.Quantity * TR.QTY / A.FACTOR Quantity,
	IIF(ISNULL(C.CRATE, 0) > 0 , C.CRATE , C.PRATE_A) RATE,
	IIF(@ItemWiseWarehouse = 1 AND ISNULL(D.WHOUSE, '') <> '' , D.WHOUSE , @Warehouse ) WAREHOUSE
	FROM  SALES_TRNPROD S
	INNER JOIN vwActiveRecipeMain A ON A.MCODE = S.MCODE
	join TRNPROD_RECEIPE TR ON A.ENO = TR.ENO AND S.VCHRNO = TR.VCHRNO AND S.SNO = TR.SNO
	INNER JOIN MENUITEM C ON tr.RMCODE = C.MCODE
	INNER JOIN MENUITEM D ON TR.PMCODE = D.MCODE
	WHERE A.FACTOR > 0 AND S.VCHRNO = @VCHRNO 
) A
