CREATE OR ALTER  PROC [dbo].[RSP_PendingConsumptionStockDetail]
--DECLARE 
@DIVISION VARCHAR(3),
@Warehouse VARCHAR(50), 
@PhiscalId VARCHAR(10),
@DATE1 DATE,
@DATE2 DATE
AS
--SELECT @DIVISION = 'BTL', @Warehouse = 'Butwal Warehouse', @PhiscalId = '80/81', @DATE1 = '1 JAN 2024', @DATE2 = '18 MAR 2024'
SET NOCOUNT ON
IF OBJECT_ID('TEMPDB..#CONSUMPTION') IS NOT NULL DROP TABLE #CONSUMPTION
IF OBJECT_ID('TEMPDB..#STOCK') IS NOT NULL DROP TABLE #STOCK

DECLARE @ItemWiseWarehouse BIT
SELECT @ItemWiseWarehouse = ItemWiseWarehouse FROM SETTING

SELECT MCODE, ITEMCODE,ITEMNAME, UNIT, CONSUMPTION, WHOUSE
INTO #CONSUMPTION
FROM
(
	SELECT B.RMCODE MCODE, C.MENUCODE ITEMCODE, C.DESCA ITEMNAME, C.BASEUNIT UNIT,  
	SUM((S.RealQty-S.RealQty_In) * B.QTY / A.FACTOR) CONSUMPTION, D.WHOUSE
	FROM vwPendingConsumptionList PC WITH (NOLOCK)
	INNER JOIN SALES_TRNPROD S WITH (NOLOCK) ON S.VCHRNO = PC.VCHRNO 
	INNER JOIN TRNPROD_RECEIPE B WITH (NOLOCK) ON S.MCODE = B.PMCODE AND S.VCHRNO = B.VCHRNO AND S.SNO = B.SNO
	INNER JOIN MENUITEM C ON B.RMCODE = C.MCODE
	INNER JOIN MENUITEM D ON B.PMCODE = D.MCODE
	INNER JOIN vwActiveRecipeMain A ON A.ENO = B.ENO
	WHERE A.FACTOR > 0 AND PC.TRNDATE BETWEEN @DATE1 AND @DATE2 AND S.DIVISION = @DIVISION AND S.PhiscalID = @PhiscalId
	GROUP BY B.RMCODE,C.MENUCODE, C.DESCA, C.BASEUNIT, D.WHOUSE
) A

SELECT MCODE, WAREHOUSE, SUM(REALQTY_IN - RealQty) STOCK INTO #STOCK FROM RMD_TRNPROD 
WHERE DIVISION = @DIVISION AND PhiscalID = @PhiscalId
GROUP BY MCODE, WAREHOUSE

SELECT C.*, STOCK, IIF(CONSUMPTION>STOCK, CONSUMPTION - STOCK, 0) SHORT FROM #CONSUMPTION C 
LEFT JOIN #STOCK SS ON C.MCODE = SS.MCODE AND IIF(@ItemWiseWarehouse = 1 AND ISNULL(WHOUSE, '') <> '' , WHOUSE , @Warehouse ) = SS.WAREHOUSE
SET NOCOUNT OFF