CREATE OR ALTER  VIEW [dbo].[vwPendingConsumptionList]
AS
SELECT ROW_NUMBER() OVER (ORDER BY A.STAMP) SNO, VCHRNO, DIVISION, TRNDATE, TRNTIME, BILLTO, NETAMNT FROM
(
	SELECT DISTINCT A.VCHRNO, A.DIVISION, A.TRNDATE, A.TRNTIME, A.BILLTO, A.NETAMNT, A.Stamp FROM
	(
		SELECT DISTINCT A.VCHRNO, A.DIVISION, A.TRNDATE, A.TRNTIME, A.BILLTO, A.NETAMNT, A.Stamp FROM SALES_TRNMAIN A WITH (NOLOCK) 
		LEFT JOIN INVMAIN B WITH (NOLOCK) ON A.VCHRNO = B.REFBILL
		LEFT JOIN excludeRecipeConsumption X WITH (NOLOCK) ON A.VCHRNO = X.VOUCHERNO
		WHERE B.VCHRNO IS NULL AND X.VOUCHERNO IS NULL
	) A
	JOIN SALES_TRNPROD P WITH (NOLOCK) ON A.VCHRNO = P.VCHRNO
	JOIN MENUITEM MI ON P.MCODE = MI.MCODE
	JOIN vwActiveRecipeMain RM ON P.MCODE = RM.MCODE
	WHERE MI.PTYPE = 10
) A 