CREATE OR ALTER  VIEW [dbo].[vwPendingConsumptionList]
AS
SELECT ROW_NUMBER() OVER (ORDER BY A.STAMP) SNO, VCHRNO, DIVISION, TRNDATE, TRNTIME, BILLTO, NETAMNT FROM
(
	SELECT DISTINCT A.VCHRNO, A.DIVISION, A.TRNDATE, A.TRNTIME, A.BILLTO, A.NETAMNT, A.Stamp FROM
	(
		SELECT DISTINCT A.VCHRNO, A.DIVISION, A.TRNDATE, A.TRNTIME, A.BILLTO, A.NETAMNT, A.Stamp, P.MCODE FROM SALES_TRNMAIN A 
		JOIN SALES_TRNPROD P ON A.VCHRNO = P.VCHRNO
		LEFT JOIN INVMAIN B ON A.VCHRNO = B.REFBILL
		WHERE B.VCHRNO IS NULL 
	) A
	JOIN MENUITEM MI ON A.MCODE = MI.MCODE
	JOIN vwActiveRecipeMain RM ON A.MCODE = RM.MCODE
	WHERE MI.PTYPE = 10
) A