CREATE OR ALTER PROC OSP_UpdateDynamicTender
AS
DECLARE @DynamicTableName NVARCHAR(255);

IF OBJECT_ID('TEMPDB..#COLS') IS NOT NULL DROP TABLE #COLS

DECLARE @columns VARCHAR(MAX), @query VARCHAR(MAX)

SELECT CONCAT('SUM(IIF(TRNMODE = ''', TRNMODE, ''', AMOUNT, 0)) ', QUOTENAME(TRNMODE)) SELECTION_COLS INTO #COLS FROM
(
	SELECT DISTINCT TRNMODE FROM vwBillTender
) A

SELECT @columns = STRING_AGG(SELECTION_COLS, ',' + CHAR(10)) FROM
(
	SELECT * FROM #COLS 
) A

SET @query = '
	CREATE OR ALTER VIEW vwDynamicTender
	AS
	SELECT VCHRNO, ' + @columns + ' FROM vwBillTender GROUP BY VCHRNO
'
PRINT @QUERY
DECLARE	@return_value int

EXEC (@QUERY)