CREATE OR ALTER VIEW vwBillTender
AS
SELECT M.VCHRNO, M.DIVISION, M.PhiscalID, M.COMPANYID, M.TERMINAL, M.VoucherType, M.TRNUSER, M.[SHIFT], M.TRNDATE, BT.TRANSACTIONID,  ISNULL(BT.TRNMODE, M.TRNMODE) TRNMODE, ISNULL(BT.AMOUNT - BT.[CHANGE], M.NETAMNT) AMOUNT  FROM RMD_TRNMAIN M 
LEFT JOIN RMD_BILLTENDER BT ON M.VCHRNO = BT.VCHRNO
WHERE M.VoucherType IN ('SI','SR','TI','CN','NR','RE')