CREATE OR ALTER    VIEW [dbo].[vwPurprod]
AS

SELECT  VCHRNO, CHALANNO, DIVISION, MCODE, HS_CODE, UNIT, Quantity, RealQty, AltQty, RATE, AMOUNT, DISCOUNT, VAT, REALRATE, EXPORT, IDIS, OPQTY, REALQTY_IN, ALTQTY_IN, WAREHOUSE, REFBILLQTY, SPRICE, 
        EXPDATE, REFOPBILL, ALTUNIT, TRNAC, PRATE, VRATE, ALTRATE, VPRATE, VSRATE, TAXABLE, NONTAXABLE, INVRATE, EXRATE, NCRATE, CRATE, SNO, CUSTOM, WEIGHT, DRATE, CARTON, INVOICENO, 
        ISSUENO, BC, GENERIC, BATCH, MFGDATE, MANUFACTURER, SERVICETAX, BCODEID, VoucherType, SALESMANID, PhiscalID, STAMP, ITEMDESC, DNID, COSTCENTER, PROMOTION, LOYALTY, INDDISCOUNT, 
        FLATDISCOUNT, NETAMOUNT, ADDTIONALROW, ISVAT, PRODCONDITION, PRODMODE, ITEMTYPE, RECEIVEDTYPE, REMARKS, RATEDISCOUNT,SCHEMESAPPLIED, ISSERVICECHARGE
FROM    dbo.PURPROD WITH (NOLOCK)

UNION ALL

SELECT VCHRNO, CHALANNO, DIVISION, MCODE, HS_CODE, UNIT, Quantity, RealQty, AltQty, RATE, AMOUNT, DISCOUNT, VAT, REALRATE, NULL EXPORT, IDIS, NULL OPQTY, REALQTY_IN, ALTQTY_IN, WAREHOUSE, REFBILLQTY, NULL SPRICE, 
        EXPDATE, NULL REFOPBILL, ALTUNIT, TRNAC, PRATE, NULL VRATE, ALTRATE, VPRATE, NULL VSRATE, TAXABLE, NONTAXABLE, NULL INVRATE, NULL EXRATE, NULL NCRATE, CRATE, SNO, NULL CUSTOM, NULL WEIGHT, NULL DRATE, NULL CARTON, INVOICENO, 
        NULL ISSUENO, BC, NULL GENERIC, BATCH, MFGDATE, MANUFACTURER, SERVICETAX, NULL BCODEID, VoucherType, NULL SALESMANID, PhiscalID, STAMP, ITEMDESC, DNID, COSTCENTER, NULL PROMOTION, NULL LOYALTY, NULL INDDISCOUNT, 
        NULL FLATDISCOUNT, NETAMOUNT, NULL ADDTIONALROW, ISVAT, NULL PRODCONDITION, NULL PRODMODE, ITEMTYPE, NULL RECEIVEDTYPE, REMARKS, NULL RATEDISCOUNT,NULL SCHEMESAPPLIED, NULL ISSERVICECHARGE
FROM     TRNPROD_NONTRADING  WITH (NOLOCK)