CREATE OR ALTER PROCEDURE [dbo].[RSP_STOCKVALUATIONREPORT] 
	@DATE2 DATETIME,			
	@PATH VARCHAR(200) ='%',	
	@FYID VARCHAR(20)='%', 
	@OPT_SHOWSUMMARY_REPORT TINYINT = 1,     --Summary:1,Detail:0
	@MCODE VARCHAR(25) = '%', 
	@DoValuation tinyint = 1, 
	@OPT_FIFO VARCHAR(1) = 'F',              --FIFO:F,LatestMRP:0
	@DIVISION VARCHAR(50)='%', 
	AS
DECLARE @DETAIL TINYINT = 1
IF @OPT_SHOWSUMMARY_REPORT=1 
	SET @DETAIL=0 
SET @PATH = @PATH + '%'
EXEC [dbo].[RSP_STOCKVALUATION_FIFO] 
		@DATE =@DATE2 ,
		@PATH =@PATH ,
		@PHISCALID =@FYID ,
		@DETAIL =@DETAIL ,
		@ITEM =@MCODE , 
		@DoValuation =@DoValuation ,
		@FIFO =@OPT_FIFO ,
		@DIVISION =@DIVISION
		@FYID = @FYID