CREATE OR ALTER  PROCEDURE [dbo].[SP_STOCKADJUSTMENTREGISTER_TIMESTAMP]
--DECLARE
	@DATE1 AS DATETIME,
	@DATE2 AS DATETIME,
	@AdjustmentBatch varchar(25) = '%',
	@DIVISION as varchar(25) = '%'
AS

--SELECT @DATE1 = GETDATE(), @DATE2 = GETDATE(), @AdjustmentBatch = 'oct 16 2024' 

DECLARE @BC_Complusory as tinyint
select @BC_Complusory = ENABLEBARCODECOMPULSORY FROM SETTING

SELECT * FROM
(
SELECT VCHRNO AS ENTRYNO, TRNDATE AS ADJDATE,BILLTOADD AS BATCH,BILLTOTEL STOCKTAKE_DATE,TRNMODE AS MODE,NULL ITEM_DESCRIPTION,NULL AS P_RATE,NULL AS PSTOC, NULL AS CSTOCK,NULL AS VARIANCE,NULL AS VARVALUE,BILLTOMOB AS WAREHOUSE, TRNUSER AS ENTRYUSER,VCHRNO AS ENO,'A' AS FLG, 'G' TYPE
FROM RMD_TRNMAIN WHERE VCHRNO LIKE 'SA%' AND DIVISION LIKE @DIVISION AND ((@AdjustmentBatch = '%' AND TRNDATE BETWEEN @DATE1 AND @DATE2) OR (@AdjustmentBatch <> '%' AND BILLTO LIKE @AdjustmentBatch))

UNION ALL

SELECT NULL,NULL,NULL,NULL,CASE WHEN @BC_Complusory = 1 THEN A.BC ELSE B.MENUCODE END BCODE, B.DESCA,CAST(A.PRATE AS VARCHAR(25)) AS PRATE,A.PSTOCK, A.CSTOCK,A.VARIANCE,A.TOTVALUE,  NULL,NULL,A.VCHRNO AS ENO,'B' AS FLAG, 'A' TYPE FROM STOCKADJUSTMENTPROD 
A, MENUITEM B, RMD_TRNMAIN C WHERE A.VCHRNO = C.VCHRNO AND A.DIVISION = C.DIVISION AND A.MCODE = B.MCODE
AND A.VCHRNO LIKE 'SA%' AND A.DIVISION LIKE @DIVISION AND ((@AdjustmentBatch = '%' AND TRNDATE BETWEEN @DATE1 AND @DATE2) OR (@AdjustmentBatch <> '%' AND BILLTO LIKE @AdjustmentBatch))


UNION ALL

SELECT NULL, NULL,NULL, NULL,NULL, NULL,NULL, NULL,NULL,NULL,NULL,NULL,NULL,VCHRNO AS ENO,'D' AS FLG, 'A' TYPE
FROM RMD_TRNMAIN WHERE VCHRNO LIKE 'SA%' AND DIVISION LIKE @DIVISION AND ((@AdjustmentBatch = '%' AND TRNDATE BETWEEN @DATE1 AND @DATE2) OR (@AdjustmentBatch <> '%' AND BILLTO LIKE @AdjustmentBatch))

UNION ALL

SELECT NULL,NULL,NULL,NULL,NULL,'TOTAL >>', NULL, SUM(A.PSTOCK) AS PSTOCK, SUM(A.CSTOCK) AS CSTOCK,SUM(A.VARIANCE) AS VARIANCE,SUM(A.TOTVALUE) AS TOTVALUE,NULL,NULL,A.VCHRNO AS ENO, 'C' AS FLAG, 'G' TYPE FROM STOCKADJUSTMENTPROD A, RMD_TRNMAIN C WHERE A.VCHRNO =C.VCHRNO AND A.DIVISION =  C.DIVISION AND A.VCHRNO LIKE 'SA%' 
 AND TRNDATE BETWEEN @DATE1 AND @DATE2 AND A.DIVISION LIKE @DIVISION AND ((@AdjustmentBatch = '%' AND TRNDATE BETWEEN @DATE1 AND @DATE2) OR (@AdjustmentBatch <> '%' AND BILLTOADD LIKE @AdjustmentBatch))
GROUP BY A.VCHRNO
) AS A
 ORDER BY ENO,FLG,ITEM_DESCRIPTION